/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class AbstractTable!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGElement.h"                 // RootElement Class

#include "OSGAbstractTableBase.h"
#include "OSGAbstractTable.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::AbstractTable
    UI AbstractTable.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Element *       AbstractTableBase::_sfRootElement
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<AbstractTable *>::_type("AbstractTablePtr", "TablePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(AbstractTable *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           AbstractTable *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           AbstractTable *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void AbstractTableBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecElementPtr::Description(
        SFUnrecElementPtr::getClassType(),
        "RootElement",
        "",
        RootElementFieldId, RootElementFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&AbstractTable::editHandleRootElement),
        static_cast<FieldGetMethodSig >(&AbstractTable::getHandleRootElement));

    oType.addInitialDesc(pDesc);
}


AbstractTableBase::TypeObject AbstractTableBase::_type(
    AbstractTableBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    NULL,
    AbstractTable::initMethod,
    AbstractTable::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&AbstractTable::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"AbstractTable\"\n"
    "\tparent=\"Table\"\n"
    "    library=\"ContribTableDom\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"false\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "UI AbstractTable.\n"
    "\t<Field\n"
    "\t\tname=\"RootElement\"\n"
    "\t\ttype=\"Element\"\n"
    "\t\tcategory=\"pointer\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"protected\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    "UI AbstractTable.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &AbstractTableBase::getType(void)
{
    return _type;
}

const FieldContainerType &AbstractTableBase::getType(void) const
{
    return _type;
}

UInt32 AbstractTableBase::getContainerSize(void) const
{
    return sizeof(AbstractTable);
}

/*------------------------- decorator get ------------------------------*/


//! Get the AbstractTable::_sfRootElement field.
const SFUnrecElementPtr *AbstractTableBase::getSFRootElement(void) const
{
    return &_sfRootElement;
}

SFUnrecElementPtr   *AbstractTableBase::editSFRootElement    (void)
{
    editSField(RootElementFieldMask);

    return &_sfRootElement;
}





/*------------------------------ access -----------------------------------*/

UInt32 AbstractTableBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (RootElementFieldMask & whichField))
    {
        returnValue += _sfRootElement.getBinSize();
    }

    return returnValue;
}

void AbstractTableBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (RootElementFieldMask & whichField))
    {
        _sfRootElement.copyToBin(pMem);
    }
}

void AbstractTableBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (RootElementFieldMask & whichField))
    {
        _sfRootElement.copyFromBin(pMem);
    }
}



/*------------------------- constructors ----------------------------------*/

AbstractTableBase::AbstractTableBase(void) :
    Inherited(),
    _sfRootElement            (NULL)
{
}

AbstractTableBase::AbstractTableBase(const AbstractTableBase &source) :
    Inherited(source),
    _sfRootElement            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

AbstractTableBase::~AbstractTableBase(void)
{
}

void AbstractTableBase::onCreate(const AbstractTable *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        AbstractTable *pThis = static_cast<AbstractTable *>(this);

        pThis->setRootElement(source->getRootElement());
    }
}

GetFieldHandlePtr AbstractTableBase::getHandleRootElement     (void) const
{
    SFUnrecElementPtr::GetHandlePtr returnValue(
        new  SFUnrecElementPtr::GetHandle(
             &_sfRootElement,
             this->getType().getFieldDesc(RootElementFieldId),
             const_cast<AbstractTableBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr AbstractTableBase::editHandleRootElement    (void)
{
    SFUnrecElementPtr::EditHandlePtr returnValue(
        new  SFUnrecElementPtr::EditHandle(
             &_sfRootElement,
             this->getType().getFieldDesc(RootElementFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&AbstractTable::setRootElement,
                    static_cast<AbstractTable *>(this), _1));

    editSField(RootElementFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void AbstractTableBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    AbstractTable *pThis = static_cast<AbstractTable *>(this);

    pThis->execSync(static_cast<AbstractTable *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void AbstractTableBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<AbstractTable *>(this)->setRootElement(NULL);


}


OSG_END_NAMESPACE
