/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGABSTRACTTABLEFIELDS_H_
#define _OSGABSTRACTTABLEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class AbstractTable;

OSG_GEN_CONTAINERPTR(AbstractTable);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<AbstractTable *> :
    public FieldTraitsFCPtrBase<AbstractTable *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<AbstractTable *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFAbstractTablePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFAbstractTablePtr"; }
};

template<> inline
const Char8 *FieldTraits<AbstractTable *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAbstractTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTable *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAbstractTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTable *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAbstractTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTable *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAbstractTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTable *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAbstractTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTable *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAbstractTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTable *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAbstractTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTable *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAbstractTablePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractTable *,
                      RecordedRefCountPolicy  > SFRecAbstractTablePtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractTable *,
                      UnrecordedRefCountPolicy> SFUnrecAbstractTablePtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractTable *,
                      WeakRefCountPolicy      > SFWeakAbstractTablePtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractTable *,
                      NoRefCountPolicy        > SFUncountedAbstractTablePtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractTable *,
                      RecordedRefCountPolicy  > MFRecAbstractTablePtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractTable *,
                      UnrecordedRefCountPolicy> MFUnrecAbstractTablePtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractTable *,
                      WeakRefCountPolicy      > MFWeakAbstractTablePtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractTable *,
                      NoRefCountPolicy        > MFUncountedAbstractTablePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecAbstractTablePtr : 
    public PointerSField<AbstractTable *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecAbstractTablePtr : 
    public PointerSField<AbstractTable *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakAbstractTablePtr :
    public PointerSField<AbstractTable *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedAbstractTablePtr :
    public PointerSField<AbstractTable *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecAbstractTablePtr :
    public PointerMField<AbstractTable *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecAbstractTablePtr :
    public PointerMField<AbstractTable *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakAbstractTablePtr :
    public PointerMField<AbstractTable *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedAbstractTablePtr :
    public PointerMField<AbstractTable *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGABSTRACTTABLEFIELDS_H_ */
