/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGABSTRACTBRANCHELEMENTFIELDS_H_
#define _OSGABSTRACTBRANCHELEMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class AbstractBranchElement;

OSG_GEN_CONTAINERPTR(AbstractBranchElement);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<AbstractBranchElement *> :
    public FieldTraitsFCPtrBase<AbstractBranchElement *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<AbstractBranchElement *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFAbstractBranchElementPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFAbstractBranchElementPtr"; }
};

template<> inline
const Char8 *FieldTraits<AbstractBranchElement *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAbstractBranchElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractBranchElement *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAbstractBranchElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractBranchElement *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAbstractBranchElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractBranchElement *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAbstractBranchElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractBranchElement *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAbstractBranchElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractBranchElement *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAbstractBranchElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractBranchElement *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAbstractBranchElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractBranchElement *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAbstractBranchElementPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractBranchElement *,
                      RecordedRefCountPolicy  > SFRecAbstractBranchElementPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractBranchElement *,
                      UnrecordedRefCountPolicy> SFUnrecAbstractBranchElementPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractBranchElement *,
                      WeakRefCountPolicy      > SFWeakAbstractBranchElementPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractBranchElement *,
                      NoRefCountPolicy        > SFUncountedAbstractBranchElementPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractBranchElement *,
                      RecordedRefCountPolicy  > MFRecAbstractBranchElementPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractBranchElement *,
                      UnrecordedRefCountPolicy> MFUnrecAbstractBranchElementPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractBranchElement *,
                      WeakRefCountPolicy      > MFWeakAbstractBranchElementPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractBranchElement *,
                      NoRefCountPolicy        > MFUncountedAbstractBranchElementPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecAbstractBranchElementPtr : 
    public PointerSField<AbstractBranchElement *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecAbstractBranchElementPtr : 
    public PointerSField<AbstractBranchElement *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakAbstractBranchElementPtr :
    public PointerSField<AbstractBranchElement *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedAbstractBranchElementPtr :
    public PointerSField<AbstractBranchElement *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecAbstractBranchElementPtr :
    public PointerMField<AbstractBranchElement *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecAbstractBranchElementPtr :
    public PointerMField<AbstractBranchElement *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakAbstractBranchElementPtr :
    public PointerMField<AbstractBranchElement *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedAbstractBranchElementPtr :
    public PointerMField<AbstractBranchElement *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGABSTRACTBRANCHELEMENTFIELDS_H_ */
