/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLEEVENTDETAILSFIELDS_H_
#define _OSGTABLEEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TableEventDetails;

OSG_GEN_CONTAINERPTR(TableEventDetails);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<TableEventDetails *> :
    public FieldTraitsFCPtrBase<TableEventDetails *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TableEventDetails *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTableEventDetailsPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTableEventDetailsPtr"; }
};

template<> inline
const Char8 *FieldTraits<TableEventDetails *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableEventDetails *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableEventDetails *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableEventDetails *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableEventDetails *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableEventDetails *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableEventDetails *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableEventDetails *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableEventDetailsPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableEventDetails *,
                      RecordedRefCountPolicy  > SFRecTableEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableEventDetails *,
                      UnrecordedRefCountPolicy> SFUnrecTableEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableEventDetails *,
                      WeakRefCountPolicy      > SFWeakTableEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableEventDetails *,
                      NoRefCountPolicy        > SFUncountedTableEventDetailsPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableEventDetails *,
                      RecordedRefCountPolicy  > MFRecTableEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableEventDetails *,
                      UnrecordedRefCountPolicy> MFUnrecTableEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableEventDetails *,
                      WeakRefCountPolicy      > MFWeakTableEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableEventDetails *,
                      NoRefCountPolicy        > MFUncountedTableEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecTableEventDetailsPtr : 
    public PointerSField<TableEventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecTableEventDetailsPtr : 
    public PointerSField<TableEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakTableEventDetailsPtr :
    public PointerSField<TableEventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedTableEventDetailsPtr :
    public PointerSField<TableEventDetails *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecTableEventDetailsPtr :
    public PointerMField<TableEventDetails *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecTableEventDetailsPtr :
    public PointerMField<TableEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakTableEventDetailsPtr :
    public PointerMField<TableEventDetails *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedTableEventDetailsPtr :
    public PointerMField<TableEventDetails *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLEEVENTDETAILSFIELDS_H_ */
