/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TableEventDetails!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGTable.h"                   // Table Class

#include "OSGTableEventDetailsBase.h"
#include "OSGTableEventDetails.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TableEventDetails
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Table *         TableEventDetailsBase::_sfTable
    
*/

/*! \var UInt32          TableEventDetailsBase::_sfRow
    
*/

/*! \var UInt32          TableEventDetailsBase::_sfColumn
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<TableEventDetails *>::_type("TableEventDetailsPtr", "EventDetailsPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(TableEventDetails *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TableEventDetails *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TableEventDetails *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TableEventDetailsBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecTablePtr::Description(
        SFUnrecTablePtr::getClassType(),
        "Table",
        "",
        TableFieldId, TableFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TableEventDetails::editHandleTable),
        static_cast<FieldGetMethodSig >(&TableEventDetails::getHandleTable));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "Row",
        "",
        RowFieldId, RowFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TableEventDetails::editHandleRow),
        static_cast<FieldGetMethodSig >(&TableEventDetails::getHandleRow));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "Column",
        "",
        ColumnFieldId, ColumnFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TableEventDetails::editHandleColumn),
        static_cast<FieldGetMethodSig >(&TableEventDetails::getHandleColumn));

    oType.addInitialDesc(pDesc);
}


TableEventDetailsBase::TypeObject TableEventDetailsBase::_type(
    TableEventDetailsBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&TableEventDetailsBase::createEmptyLocal),
    TableEventDetails::initMethod,
    TableEventDetails::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TableEventDetails::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"TableEventDetails\"\n"
    "\tparent=\"EventDetails\"\n"
    "    library=\"ContribTableDom\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    isBundle=\"true\"\n"
    "\tsupportUnregisteredCreate=\"true\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "\t<Field\n"
    "\t\tname=\"Table\"\n"
    "\t\ttype=\"Table\"\n"
    "\t\tcategory=\"pointer\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"protected\"\n"
    "\t\tdefaultValue=\"NULL\"\n"
    "        publicRead=\"true\"\n"
    "\t>\n"
    "\t</Field>\n"
    "\t<Field\n"
    "\t\tname=\"Row\"\n"
    "\t\ttype=\"UInt32\"\n"
    "\t\tcategory=\"data\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"protected\"\n"
    "\t\tdefaultValue=\"0\"\n"
    "        publicRead=\"true\"\n"
    "\t>\n"
    "\t</Field>\n"
    "\t<Field\n"
    "\t\tname=\"Column\"\n"
    "\t\ttype=\"UInt32\"\n"
    "\t\tcategory=\"data\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"protected\"\n"
    "\t\tdefaultValue=\"0\"\n"
    "        publicRead=\"true\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TableEventDetailsBase::getType(void)
{
    return _type;
}

const FieldContainerType &TableEventDetailsBase::getType(void) const
{
    return _type;
}

UInt32 TableEventDetailsBase::getContainerSize(void) const
{
    return sizeof(TableEventDetails);
}

/*------------------------- decorator get ------------------------------*/


//! Get the TableEventDetails::_sfTable field.
const SFUnrecTablePtr *TableEventDetailsBase::getSFTable(void) const
{
    return &_sfTable;
}

SFUnrecTablePtr     *TableEventDetailsBase::editSFTable          (void)
{
    editSField(TableFieldMask);

    return &_sfTable;
}

SFUInt32 *TableEventDetailsBase::editSFRow(void)
{
    editSField(RowFieldMask);

    return &_sfRow;
}

const SFUInt32 *TableEventDetailsBase::getSFRow(void) const
{
    return &_sfRow;
}


SFUInt32 *TableEventDetailsBase::editSFColumn(void)
{
    editSField(ColumnFieldMask);

    return &_sfColumn;
}

const SFUInt32 *TableEventDetailsBase::getSFColumn(void) const
{
    return &_sfColumn;
}






/*------------------------------ access -----------------------------------*/

UInt32 TableEventDetailsBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (TableFieldMask & whichField))
    {
        returnValue += _sfTable.getBinSize();
    }
    if(FieldBits::NoField != (RowFieldMask & whichField))
    {
        returnValue += _sfRow.getBinSize();
    }
    if(FieldBits::NoField != (ColumnFieldMask & whichField))
    {
        returnValue += _sfColumn.getBinSize();
    }

    return returnValue;
}

void TableEventDetailsBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (TableFieldMask & whichField))
    {
        _sfTable.copyToBin(pMem);
    }
    if(FieldBits::NoField != (RowFieldMask & whichField))
    {
        _sfRow.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ColumnFieldMask & whichField))
    {
        _sfColumn.copyToBin(pMem);
    }
}

void TableEventDetailsBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (TableFieldMask & whichField))
    {
        _sfTable.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (RowFieldMask & whichField))
    {
        _sfRow.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ColumnFieldMask & whichField))
    {
        _sfColumn.copyFromBin(pMem);
    }
}

//! create a new instance of the class
TableEventDetailsTransitPtr TableEventDetailsBase::createLocal(BitVector bFlags)
{
    TableEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TableEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TableEventDetailsTransitPtr TableEventDetailsBase::createDependent(BitVector bFlags)
{
    TableEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TableEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TableEventDetailsTransitPtr TableEventDetailsBase::create(void)
{
    return createLocal();
}

TableEventDetails *TableEventDetailsBase::createEmptyLocal(BitVector bFlags)
{
    TableEventDetails *returnValue;

    newPtr<TableEventDetails>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TableEventDetails *TableEventDetailsBase::createEmpty(void)
{
    return createEmptyLocal();
}

TableEventDetails *TableEventDetailsBase::createUnregistered(void)
{
    TableEventDetails *returnValue = new TableEventDetails;

#ifdef OSG_MT_CPTR_ASPECT
    returnValue->setupAspectStore();
#endif
    //Do not register with the FieldContainer Factory

    returnValue->onCreate      (      );
    returnValue->onCreateAspect(returnValue);
    
    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();
    
    return returnValue;
}

FieldContainerTransitPtr TableEventDetailsBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TableEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TableEventDetails *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TableEventDetailsBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TableEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TableEventDetails *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TableEventDetailsBase::shallowCopy(void) const
{
    return shallowCopyLocal();
}



/*------------------------- constructors ----------------------------------*/

TableEventDetailsBase::TableEventDetailsBase(void) :
    Inherited(),
    _sfTable                  (NULL),
    _sfRow                    (UInt32(0)),
    _sfColumn                 (UInt32(0))
{
}

TableEventDetailsBase::TableEventDetailsBase(const TableEventDetailsBase &source) :
    Inherited(source),
    _sfTable                  (NULL),
    _sfRow                    (source._sfRow                    ),
    _sfColumn                 (source._sfColumn                 )
{
}


/*-------------------------- destructors ----------------------------------*/

TableEventDetailsBase::~TableEventDetailsBase(void)
{
}

void TableEventDetailsBase::onCreate(const TableEventDetails *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        TableEventDetails *pThis = static_cast<TableEventDetails *>(this);

        pThis->setTable(source->getTable());
    }
}

GetFieldHandlePtr TableEventDetailsBase::getHandleTable           (void) const
{
    SFUnrecTablePtr::GetHandlePtr returnValue(
        new  SFUnrecTablePtr::GetHandle(
             &_sfTable,
             this->getType().getFieldDesc(TableFieldId),
             const_cast<TableEventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TableEventDetailsBase::editHandleTable          (void)
{
    SFUnrecTablePtr::EditHandlePtr returnValue(
        new  SFUnrecTablePtr::EditHandle(
             &_sfTable,
             this->getType().getFieldDesc(TableFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&TableEventDetails::setTable,
                    static_cast<TableEventDetails *>(this), _1));

    editSField(TableFieldMask);

    return returnValue;
}

GetFieldHandlePtr TableEventDetailsBase::getHandleRow             (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfRow,
             this->getType().getFieldDesc(RowFieldId),
             const_cast<TableEventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TableEventDetailsBase::editHandleRow            (void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfRow,
             this->getType().getFieldDesc(RowFieldId),
             this));


    editSField(RowFieldMask);

    return returnValue;
}

GetFieldHandlePtr TableEventDetailsBase::getHandleColumn          (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfColumn,
             this->getType().getFieldDesc(ColumnFieldId),
             const_cast<TableEventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TableEventDetailsBase::editHandleColumn         (void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfColumn,
             this->getType().getFieldDesc(ColumnFieldId),
             this));


    editSField(ColumnFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void TableEventDetailsBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TableEventDetails *pThis = static_cast<TableEventDetails *>(this);

    pThis->execSync(static_cast<TableEventDetails *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TableEventDetailsBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TableEventDetails *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TableEventDetails *>(pRefAspect),
                  dynamic_cast<const TableEventDetails *>(this));

    return returnValue;
}
#endif

void TableEventDetailsBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<TableEventDetails *>(this)->setTable(NULL);


}


OSG_END_NAMESPACE
