/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletBvhTriangleMeshShape!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGNode.h"                    // GeometryNode Class

#include "OSGBulletBvhTriangleMeshShapeBase.h"
#include "OSGBulletBvhTriangleMeshShape.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletBvhTriangleMeshShape
    This core is a wrapper around the bullet btBvhTriangleMeshShape.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Node *          BulletBvhTriangleMeshShapeBase::_sfGeometryNode
    this node should contain a geometrynode core with geo data.
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletBvhTriangleMeshShape *>::_type("BulletBvhTriangleMeshShapePtr", "BulletCollisionShapePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletBvhTriangleMeshShape *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletBvhTriangleMeshShape *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BulletBvhTriangleMeshShape *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletBvhTriangleMeshShapeBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecNodePtr::Description(
        SFUnrecNodePtr::getClassType(),
        "GeometryNode",
        "this node should contain a geometrynode core with geo data.\n",
        GeometryNodeFieldId, GeometryNodeFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletBvhTriangleMeshShape::editHandleGeometryNode),
        static_cast<FieldGetMethodSig >(&BulletBvhTriangleMeshShape::getHandleGeometryNode));

    oType.addInitialDesc(pDesc);
}


BulletBvhTriangleMeshShapeBase::TypeObject BulletBvhTriangleMeshShapeBase::_type(
    BulletBvhTriangleMeshShapeBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletBvhTriangleMeshShapeBase::createEmptyLocal),
    BulletBvhTriangleMeshShape::initMethod,
    BulletBvhTriangleMeshShape::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletBvhTriangleMeshShape::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BulletBvhTriangleMeshShape\"\n"
    "    parent=\"BulletCollisionShape\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet btBvhTriangleMeshShape.\n"
    "    <Field\n"
    "        name=\"GeometryNode\"\n"
    "        type=\"Node\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"NULL\"\n"
    "    >\n"
    "    this node should contain a geometrynode core with geo data.\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet btBvhTriangleMeshShape.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletBvhTriangleMeshShapeBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletBvhTriangleMeshShapeBase::getType(void) const
{
    return _type;
}

UInt32 BulletBvhTriangleMeshShapeBase::getContainerSize(void) const
{
    return sizeof(BulletBvhTriangleMeshShape);
}

/*------------------------- decorator get ------------------------------*/


//! Get the BulletBvhTriangleMeshShape::_sfGeometryNode field.
const SFUnrecNodePtr *BulletBvhTriangleMeshShapeBase::getSFGeometryNode(void) const
{
    return &_sfGeometryNode;
}

SFUnrecNodePtr      *BulletBvhTriangleMeshShapeBase::editSFGeometryNode   (void)
{
    editSField(GeometryNodeFieldMask);

    return &_sfGeometryNode;
}





/*------------------------------ access -----------------------------------*/

UInt32 BulletBvhTriangleMeshShapeBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (GeometryNodeFieldMask & whichField))
    {
        returnValue += _sfGeometryNode.getBinSize();
    }

    return returnValue;
}

void BulletBvhTriangleMeshShapeBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (GeometryNodeFieldMask & whichField))
    {
        _sfGeometryNode.copyToBin(pMem);
    }
}

void BulletBvhTriangleMeshShapeBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (GeometryNodeFieldMask & whichField))
    {
        editSField(GeometryNodeFieldMask);
        _sfGeometryNode.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BulletBvhTriangleMeshShapeTransitPtr BulletBvhTriangleMeshShapeBase::createLocal(BitVector bFlags)
{
    BulletBvhTriangleMeshShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletBvhTriangleMeshShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletBvhTriangleMeshShapeTransitPtr BulletBvhTriangleMeshShapeBase::createDependent(BitVector bFlags)
{
    BulletBvhTriangleMeshShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletBvhTriangleMeshShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletBvhTriangleMeshShapeTransitPtr BulletBvhTriangleMeshShapeBase::create(void)
{
    BulletBvhTriangleMeshShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BulletBvhTriangleMeshShape>(tmpPtr);
    }

    return fc;
}

BulletBvhTriangleMeshShape *BulletBvhTriangleMeshShapeBase::createEmptyLocal(BitVector bFlags)
{
    BulletBvhTriangleMeshShape *returnValue;

    newPtr<BulletBvhTriangleMeshShape>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletBvhTriangleMeshShape *BulletBvhTriangleMeshShapeBase::createEmpty(void)
{
    BulletBvhTriangleMeshShape *returnValue;

    newPtr<BulletBvhTriangleMeshShape>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr BulletBvhTriangleMeshShapeBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletBvhTriangleMeshShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletBvhTriangleMeshShape *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletBvhTriangleMeshShapeBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletBvhTriangleMeshShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletBvhTriangleMeshShape *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletBvhTriangleMeshShapeBase::shallowCopy(void) const
{
    BulletBvhTriangleMeshShape *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BulletBvhTriangleMeshShape *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BulletBvhTriangleMeshShapeBase::BulletBvhTriangleMeshShapeBase(void) :
    Inherited(),
    _sfGeometryNode           (NULL)
{
}

BulletBvhTriangleMeshShapeBase::BulletBvhTriangleMeshShapeBase(const BulletBvhTriangleMeshShapeBase &source) :
    Inherited(source),
    _sfGeometryNode           (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

BulletBvhTriangleMeshShapeBase::~BulletBvhTriangleMeshShapeBase(void)
{
}

void BulletBvhTriangleMeshShapeBase::onCreate(const BulletBvhTriangleMeshShape *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        BulletBvhTriangleMeshShape *pThis = static_cast<BulletBvhTriangleMeshShape *>(this);

        pThis->setGeometryNode(source->getGeometryNode());
    }
}

GetFieldHandlePtr BulletBvhTriangleMeshShapeBase::getHandleGeometryNode    (void) const
{
    SFUnrecNodePtr::GetHandlePtr returnValue(
        new  SFUnrecNodePtr::GetHandle(
             &_sfGeometryNode,
             this->getType().getFieldDesc(GeometryNodeFieldId),
             const_cast<BulletBvhTriangleMeshShapeBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletBvhTriangleMeshShapeBase::editHandleGeometryNode   (void)
{
    SFUnrecNodePtr::EditHandlePtr returnValue(
        new  SFUnrecNodePtr::EditHandle(
             &_sfGeometryNode,
             this->getType().getFieldDesc(GeometryNodeFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&BulletBvhTriangleMeshShape::setGeometryNode,
                    static_cast<BulletBvhTriangleMeshShape *>(this), _1));

    editSField(GeometryNodeFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void BulletBvhTriangleMeshShapeBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletBvhTriangleMeshShape *pThis = static_cast<BulletBvhTriangleMeshShape *>(this);

    pThis->execSync(static_cast<BulletBvhTriangleMeshShape *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletBvhTriangleMeshShapeBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletBvhTriangleMeshShape *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletBvhTriangleMeshShape *>(pRefAspect),
                  dynamic_cast<const BulletBvhTriangleMeshShape *>(this));

    return returnValue;
}
#endif

void BulletBvhTriangleMeshShapeBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<BulletBvhTriangleMeshShape *>(this)->setGeometryNode(NULL);


}


OSG_END_NAMESPACE
