/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETGIMPACTMESHSHAPEFIELDS_H_
#define _OSGBULLETGIMPACTMESHSHAPEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletGImpactMeshShape;

OSG_GEN_CONTAINERPTR(BulletGImpactMeshShape);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletGImpactMeshShape *> :
    public FieldTraitsFCPtrBase<BulletGImpactMeshShape *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletGImpactMeshShape *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletGImpactMeshShapePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletGImpactMeshShapePtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletGImpactMeshShape *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletGImpactMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGImpactMeshShape *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletGImpactMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGImpactMeshShape *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletGImpactMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGImpactMeshShape *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletGImpactMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGImpactMeshShape *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletGImpactMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGImpactMeshShape *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletGImpactMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGImpactMeshShape *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletGImpactMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGImpactMeshShape *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletGImpactMeshShapePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletGImpactMeshShape *,
                      RecordedRefCountPolicy  > SFRecBulletGImpactMeshShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletGImpactMeshShape *,
                      UnrecordedRefCountPolicy> SFUnrecBulletGImpactMeshShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletGImpactMeshShape *,
                      WeakRefCountPolicy      > SFWeakBulletGImpactMeshShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletGImpactMeshShape *,
                      NoRefCountPolicy        > SFUncountedBulletGImpactMeshShapePtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletGImpactMeshShape *,
                      RecordedRefCountPolicy  > MFRecBulletGImpactMeshShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletGImpactMeshShape *,
                      UnrecordedRefCountPolicy> MFUnrecBulletGImpactMeshShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletGImpactMeshShape *,
                      WeakRefCountPolicy      > MFWeakBulletGImpactMeshShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletGImpactMeshShape *,
                      NoRefCountPolicy        > MFUncountedBulletGImpactMeshShapePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletGImpactMeshShapePtr : 
    public PointerSField<BulletGImpactMeshShape *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletGImpactMeshShapePtr : 
    public PointerSField<BulletGImpactMeshShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletGImpactMeshShapePtr :
    public PointerSField<BulletGImpactMeshShape *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletGImpactMeshShapePtr :
    public PointerSField<BulletGImpactMeshShape *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletGImpactMeshShapePtr :
    public PointerMField<BulletGImpactMeshShape *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletGImpactMeshShapePtr :
    public PointerMField<BulletGImpactMeshShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletGImpactMeshShapePtr :
    public PointerMField<BulletGImpactMeshShape *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletGImpactMeshShapePtr :
    public PointerMField<BulletGImpactMeshShape *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETGIMPACTMESHSHAPEFIELDS_H_ */
