/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletGImpactMeshShape!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGNode.h"                    // GeometryNode Class

#include "OSGBulletGImpactMeshShapeBase.h"
#include "OSGBulletGImpactMeshShape.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletGImpactMeshShape
    This core is a wrapper around the bullet btGImpactMeshShape.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Node *          BulletGImpactMeshShapeBase::_sfGeometryNode
    this node should contain a geometrynode core with geo data.
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletGImpactMeshShape *>::_type("BulletGImpactMeshShapePtr", "BulletCollisionShapePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletGImpactMeshShape *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletGImpactMeshShape *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BulletGImpactMeshShape *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletGImpactMeshShapeBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecNodePtr::Description(
        SFUnrecNodePtr::getClassType(),
        "GeometryNode",
        "this node should contain a geometrynode core with geo data.\n",
        GeometryNodeFieldId, GeometryNodeFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletGImpactMeshShape::editHandleGeometryNode),
        static_cast<FieldGetMethodSig >(&BulletGImpactMeshShape::getHandleGeometryNode));

    oType.addInitialDesc(pDesc);
}


BulletGImpactMeshShapeBase::TypeObject BulletGImpactMeshShapeBase::_type(
    BulletGImpactMeshShapeBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletGImpactMeshShapeBase::createEmptyLocal),
    BulletGImpactMeshShape::initMethod,
    BulletGImpactMeshShape::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletGImpactMeshShape::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BulletGImpactMeshShape\"\n"
    "    parent=\"BulletCollisionShape\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet btGImpactMeshShape.\n"
    "    <Field\n"
    "        name=\"GeometryNode\"\n"
    "        type=\"Node\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"NULL\"\n"
    "    >\n"
    "    this node should contain a geometrynode core with geo data.\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet btGImpactMeshShape.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletGImpactMeshShapeBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletGImpactMeshShapeBase::getType(void) const
{
    return _type;
}

UInt32 BulletGImpactMeshShapeBase::getContainerSize(void) const
{
    return sizeof(BulletGImpactMeshShape);
}

/*------------------------- decorator get ------------------------------*/


//! Get the BulletGImpactMeshShape::_sfGeometryNode field.
const SFUnrecNodePtr *BulletGImpactMeshShapeBase::getSFGeometryNode(void) const
{
    return &_sfGeometryNode;
}

SFUnrecNodePtr      *BulletGImpactMeshShapeBase::editSFGeometryNode   (void)
{
    editSField(GeometryNodeFieldMask);

    return &_sfGeometryNode;
}





/*------------------------------ access -----------------------------------*/

UInt32 BulletGImpactMeshShapeBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (GeometryNodeFieldMask & whichField))
    {
        returnValue += _sfGeometryNode.getBinSize();
    }

    return returnValue;
}

void BulletGImpactMeshShapeBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (GeometryNodeFieldMask & whichField))
    {
        _sfGeometryNode.copyToBin(pMem);
    }
}

void BulletGImpactMeshShapeBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (GeometryNodeFieldMask & whichField))
    {
        editSField(GeometryNodeFieldMask);
        _sfGeometryNode.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BulletGImpactMeshShapeTransitPtr BulletGImpactMeshShapeBase::createLocal(BitVector bFlags)
{
    BulletGImpactMeshShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletGImpactMeshShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletGImpactMeshShapeTransitPtr BulletGImpactMeshShapeBase::createDependent(BitVector bFlags)
{
    BulletGImpactMeshShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletGImpactMeshShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletGImpactMeshShapeTransitPtr BulletGImpactMeshShapeBase::create(void)
{
    BulletGImpactMeshShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BulletGImpactMeshShape>(tmpPtr);
    }

    return fc;
}

BulletGImpactMeshShape *BulletGImpactMeshShapeBase::createEmptyLocal(BitVector bFlags)
{
    BulletGImpactMeshShape *returnValue;

    newPtr<BulletGImpactMeshShape>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletGImpactMeshShape *BulletGImpactMeshShapeBase::createEmpty(void)
{
    BulletGImpactMeshShape *returnValue;

    newPtr<BulletGImpactMeshShape>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr BulletGImpactMeshShapeBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletGImpactMeshShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletGImpactMeshShape *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletGImpactMeshShapeBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletGImpactMeshShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletGImpactMeshShape *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletGImpactMeshShapeBase::shallowCopy(void) const
{
    BulletGImpactMeshShape *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BulletGImpactMeshShape *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BulletGImpactMeshShapeBase::BulletGImpactMeshShapeBase(void) :
    Inherited(),
    _sfGeometryNode           (NULL)
{
}

BulletGImpactMeshShapeBase::BulletGImpactMeshShapeBase(const BulletGImpactMeshShapeBase &source) :
    Inherited(source),
    _sfGeometryNode           (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

BulletGImpactMeshShapeBase::~BulletGImpactMeshShapeBase(void)
{
}

void BulletGImpactMeshShapeBase::onCreate(const BulletGImpactMeshShape *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        BulletGImpactMeshShape *pThis = static_cast<BulletGImpactMeshShape *>(this);

        pThis->setGeometryNode(source->getGeometryNode());
    }
}

GetFieldHandlePtr BulletGImpactMeshShapeBase::getHandleGeometryNode    (void) const
{
    SFUnrecNodePtr::GetHandlePtr returnValue(
        new  SFUnrecNodePtr::GetHandle(
             &_sfGeometryNode,
             this->getType().getFieldDesc(GeometryNodeFieldId),
             const_cast<BulletGImpactMeshShapeBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletGImpactMeshShapeBase::editHandleGeometryNode   (void)
{
    SFUnrecNodePtr::EditHandlePtr returnValue(
        new  SFUnrecNodePtr::EditHandle(
             &_sfGeometryNode,
             this->getType().getFieldDesc(GeometryNodeFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&BulletGImpactMeshShape::setGeometryNode,
                    static_cast<BulletGImpactMeshShape *>(this), _1));

    editSField(GeometryNodeFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void BulletGImpactMeshShapeBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletGImpactMeshShape *pThis = static_cast<BulletGImpactMeshShape *>(this);

    pThis->execSync(static_cast<BulletGImpactMeshShape *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletGImpactMeshShapeBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletGImpactMeshShape *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletGImpactMeshShape *>(pRefAspect),
                  dynamic_cast<const BulletGImpactMeshShape *>(this));

    return returnValue;
}
#endif

void BulletGImpactMeshShapeBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<BulletGImpactMeshShape *>(this)->setGeometryNode(NULL);


}


OSG_END_NAMESPACE
