/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETBVHTRIANGLEMESHSHAPEFIELDS_H_
#define _OSGBULLETBVHTRIANGLEMESHSHAPEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletBvhTriangleMeshShape;

OSG_GEN_CONTAINERPTR(BulletBvhTriangleMeshShape);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletBvhTriangleMeshShape *> :
    public FieldTraitsFCPtrBase<BulletBvhTriangleMeshShape *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletBvhTriangleMeshShape *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletBvhTriangleMeshShapePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletBvhTriangleMeshShapePtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletBvhTriangleMeshShape *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletBvhTriangleMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletBvhTriangleMeshShape *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletBvhTriangleMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletBvhTriangleMeshShape *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletBvhTriangleMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletBvhTriangleMeshShape *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletBvhTriangleMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletBvhTriangleMeshShape *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletBvhTriangleMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletBvhTriangleMeshShape *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletBvhTriangleMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletBvhTriangleMeshShape *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletBvhTriangleMeshShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletBvhTriangleMeshShape *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletBvhTriangleMeshShapePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletBvhTriangleMeshShape *,
                      RecordedRefCountPolicy  > SFRecBulletBvhTriangleMeshShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletBvhTriangleMeshShape *,
                      UnrecordedRefCountPolicy> SFUnrecBulletBvhTriangleMeshShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletBvhTriangleMeshShape *,
                      WeakRefCountPolicy      > SFWeakBulletBvhTriangleMeshShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletBvhTriangleMeshShape *,
                      NoRefCountPolicy        > SFUncountedBulletBvhTriangleMeshShapePtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletBvhTriangleMeshShape *,
                      RecordedRefCountPolicy  > MFRecBulletBvhTriangleMeshShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletBvhTriangleMeshShape *,
                      UnrecordedRefCountPolicy> MFUnrecBulletBvhTriangleMeshShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletBvhTriangleMeshShape *,
                      WeakRefCountPolicy      > MFWeakBulletBvhTriangleMeshShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletBvhTriangleMeshShape *,
                      NoRefCountPolicy        > MFUncountedBulletBvhTriangleMeshShapePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletBvhTriangleMeshShapePtr : 
    public PointerSField<BulletBvhTriangleMeshShape *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletBvhTriangleMeshShapePtr : 
    public PointerSField<BulletBvhTriangleMeshShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletBvhTriangleMeshShapePtr :
    public PointerSField<BulletBvhTriangleMeshShape *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletBvhTriangleMeshShapePtr :
    public PointerSField<BulletBvhTriangleMeshShape *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletBvhTriangleMeshShapePtr :
    public PointerMField<BulletBvhTriangleMeshShape *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletBvhTriangleMeshShapePtr :
    public PointerMField<BulletBvhTriangleMeshShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletBvhTriangleMeshShapePtr :
    public PointerMField<BulletBvhTriangleMeshShape *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletBvhTriangleMeshShapePtr :
    public PointerMField<BulletBvhTriangleMeshShape *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETBVHTRIANGLEMESHSHAPEFIELDS_H_ */
