/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletGpu3DGridBroadphase!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBulletGpu3DGridBroadphaseBase.h"
#include "OSGBulletGpu3DGridBroadphase.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletGpu3DGridBroadphase
    This core is a wrapper around the bullet btGpu3DGridBroadphase.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletGpu3DGridBroadphase *>::_type("BulletGpu3DGridBroadphasePtr", "BulletBroadphaseInterfacePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletGpu3DGridBroadphase *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletGpu3DGridBroadphase *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BulletGpu3DGridBroadphase *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletGpu3DGridBroadphaseBase::classDescInserter(TypeObject &oType)
{
}


BulletGpu3DGridBroadphaseBase::TypeObject BulletGpu3DGridBroadphaseBase::_type(
    BulletGpu3DGridBroadphaseBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletGpu3DGridBroadphaseBase::createEmptyLocal),
    BulletGpu3DGridBroadphase::initMethod,
    BulletGpu3DGridBroadphase::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletGpu3DGridBroadphase::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BulletGpu3DGridBroadphase\"\n"
    "    parent=\"BulletBroadphaseInterface\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet btGpu3DGridBroadphase.\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet btGpu3DGridBroadphase.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletGpu3DGridBroadphaseBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletGpu3DGridBroadphaseBase::getType(void) const
{
    return _type;
}

UInt32 BulletGpu3DGridBroadphaseBase::getContainerSize(void) const
{
    return sizeof(BulletGpu3DGridBroadphase);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 BulletGpu3DGridBroadphaseBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void BulletGpu3DGridBroadphaseBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void BulletGpu3DGridBroadphaseBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
BulletGpu3DGridBroadphaseTransitPtr BulletGpu3DGridBroadphaseBase::createLocal(BitVector bFlags)
{
    BulletGpu3DGridBroadphaseTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletGpu3DGridBroadphase>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletGpu3DGridBroadphaseTransitPtr BulletGpu3DGridBroadphaseBase::createDependent(BitVector bFlags)
{
    BulletGpu3DGridBroadphaseTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletGpu3DGridBroadphase>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletGpu3DGridBroadphaseTransitPtr BulletGpu3DGridBroadphaseBase::create(void)
{
    BulletGpu3DGridBroadphaseTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BulletGpu3DGridBroadphase>(tmpPtr);
    }

    return fc;
}

BulletGpu3DGridBroadphase *BulletGpu3DGridBroadphaseBase::createEmptyLocal(BitVector bFlags)
{
    BulletGpu3DGridBroadphase *returnValue;

    newPtr<BulletGpu3DGridBroadphase>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletGpu3DGridBroadphase *BulletGpu3DGridBroadphaseBase::createEmpty(void)
{
    BulletGpu3DGridBroadphase *returnValue;

    newPtr<BulletGpu3DGridBroadphase>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr BulletGpu3DGridBroadphaseBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletGpu3DGridBroadphase *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletGpu3DGridBroadphase *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletGpu3DGridBroadphaseBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletGpu3DGridBroadphase *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletGpu3DGridBroadphase *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletGpu3DGridBroadphaseBase::shallowCopy(void) const
{
    BulletGpu3DGridBroadphase *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BulletGpu3DGridBroadphase *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BulletGpu3DGridBroadphaseBase::BulletGpu3DGridBroadphaseBase(void) :
    Inherited()
{
}

BulletGpu3DGridBroadphaseBase::BulletGpu3DGridBroadphaseBase(const BulletGpu3DGridBroadphaseBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

BulletGpu3DGridBroadphaseBase::~BulletGpu3DGridBroadphaseBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void BulletGpu3DGridBroadphaseBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletGpu3DGridBroadphase *pThis = static_cast<BulletGpu3DGridBroadphase *>(this);

    pThis->execSync(static_cast<BulletGpu3DGridBroadphase *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletGpu3DGridBroadphaseBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletGpu3DGridBroadphase *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletGpu3DGridBroadphase *>(pRefAspect),
                  dynamic_cast<const BulletGpu3DGridBroadphase *>(this));

    return returnValue;
}
#endif

void BulletGpu3DGridBroadphaseBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
