/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETGPU3DGRIDBROADPHASEFIELDS_H_
#define _OSGBULLETGPU3DGRIDBROADPHASEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletGpu3DGridBroadphase;

OSG_GEN_CONTAINERPTR(BulletGpu3DGridBroadphase);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletGpu3DGridBroadphase *> :
    public FieldTraitsFCPtrBase<BulletGpu3DGridBroadphase *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletGpu3DGridBroadphase *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletGpu3DGridBroadphasePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletGpu3DGridBroadphasePtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletGpu3DGridBroadphase *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletGpu3DGridBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGpu3DGridBroadphase *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletGpu3DGridBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGpu3DGridBroadphase *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletGpu3DGridBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGpu3DGridBroadphase *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletGpu3DGridBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGpu3DGridBroadphase *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletGpu3DGridBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGpu3DGridBroadphase *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletGpu3DGridBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGpu3DGridBroadphase *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletGpu3DGridBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletGpu3DGridBroadphase *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletGpu3DGridBroadphasePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletGpu3DGridBroadphase *,
                      RecordedRefCountPolicy  > SFRecBulletGpu3DGridBroadphasePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletGpu3DGridBroadphase *,
                      UnrecordedRefCountPolicy> SFUnrecBulletGpu3DGridBroadphasePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletGpu3DGridBroadphase *,
                      WeakRefCountPolicy      > SFWeakBulletGpu3DGridBroadphasePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletGpu3DGridBroadphase *,
                      NoRefCountPolicy        > SFUncountedBulletGpu3DGridBroadphasePtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletGpu3DGridBroadphase *,
                      RecordedRefCountPolicy  > MFRecBulletGpu3DGridBroadphasePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletGpu3DGridBroadphase *,
                      UnrecordedRefCountPolicy> MFUnrecBulletGpu3DGridBroadphasePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletGpu3DGridBroadphase *,
                      WeakRefCountPolicy      > MFWeakBulletGpu3DGridBroadphasePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletGpu3DGridBroadphase *,
                      NoRefCountPolicy        > MFUncountedBulletGpu3DGridBroadphasePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletGpu3DGridBroadphasePtr : 
    public PointerSField<BulletGpu3DGridBroadphase *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletGpu3DGridBroadphasePtr : 
    public PointerSField<BulletGpu3DGridBroadphase *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletGpu3DGridBroadphasePtr :
    public PointerSField<BulletGpu3DGridBroadphase *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletGpu3DGridBroadphasePtr :
    public PointerSField<BulletGpu3DGridBroadphase *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletGpu3DGridBroadphasePtr :
    public PointerMField<BulletGpu3DGridBroadphase *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletGpu3DGridBroadphasePtr :
    public PointerMField<BulletGpu3DGridBroadphase *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletGpu3DGridBroadphasePtr :
    public PointerMField<BulletGpu3DGridBroadphase *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletGpu3DGridBroadphasePtr :
    public PointerMField<BulletGpu3DGridBroadphase *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETGPU3DGRIDBROADPHASEFIELDS_H_ */
