/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala*
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class VariableHeightLayoutManager!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OpenSG/OSGConfig.h"




#include "OSGVariableHeightLayoutManagerBase.h"
#include "OSGVariableHeightLayoutManager.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::VariableHeightLayoutManager
    A UI VariableHeightLayoutManager
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<VariableHeightLayoutManager *>::_type("VariableHeightLayoutManagerPtr", "TableDomLayoutManagerPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(VariableHeightLayoutManager *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           VariableHeightLayoutManager *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           VariableHeightLayoutManager *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void VariableHeightLayoutManagerBase::classDescInserter(TypeObject &oType)
{
}


VariableHeightLayoutManagerBase::TypeObject VariableHeightLayoutManagerBase::_type(
    VariableHeightLayoutManagerBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&VariableHeightLayoutManagerBase::createEmptyLocal),
    VariableHeightLayoutManager::initMethod,
    VariableHeightLayoutManager::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&VariableHeightLayoutManager::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"VariableHeightLayoutManager\"\n"
    "\tparent=\"TableDomLayoutManager\"\n"
    "\tlibrary=\"ContribTableDom\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"true\"\n"
    "\tisNodeCore=\"false\"\n"
    "    \tauthors=\"David Kabala\"\n"
    ">\n"
    "\n"
    "A UI VariableHeightLayoutManager\n"
    "\n"
    "\n"
    "</FieldContainer>\n",
    "A UI VariableHeightLayoutManager\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &VariableHeightLayoutManagerBase::getType(void)
{
    return _type;
}

const FieldContainerType &VariableHeightLayoutManagerBase::getType(void) const
{
    return _type;
}

UInt32 VariableHeightLayoutManagerBase::getContainerSize(void) const
{
    return sizeof(VariableHeightLayoutManager);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 VariableHeightLayoutManagerBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void VariableHeightLayoutManagerBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void VariableHeightLayoutManagerBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
VariableHeightLayoutManagerTransitPtr VariableHeightLayoutManagerBase::createLocal(BitVector bFlags)
{
    VariableHeightLayoutManagerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<VariableHeightLayoutManager>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
VariableHeightLayoutManagerTransitPtr VariableHeightLayoutManagerBase::createDependent(BitVector bFlags)
{
    VariableHeightLayoutManagerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<VariableHeightLayoutManager>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
VariableHeightLayoutManagerTransitPtr VariableHeightLayoutManagerBase::create(void)
{
    VariableHeightLayoutManagerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<VariableHeightLayoutManager>(tmpPtr);
    }

    return fc;
}

VariableHeightLayoutManager *VariableHeightLayoutManagerBase::createEmptyLocal(BitVector bFlags)
{
    VariableHeightLayoutManager *returnValue;

    newPtr<VariableHeightLayoutManager>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
VariableHeightLayoutManager *VariableHeightLayoutManagerBase::createEmpty(void)
{
    VariableHeightLayoutManager *returnValue;

    newPtr<VariableHeightLayoutManager>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr VariableHeightLayoutManagerBase::shallowCopyLocal(
    BitVector bFlags) const
{
    VariableHeightLayoutManager *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const VariableHeightLayoutManager *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr VariableHeightLayoutManagerBase::shallowCopyDependent(
    BitVector bFlags) const
{
    VariableHeightLayoutManager *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const VariableHeightLayoutManager *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr VariableHeightLayoutManagerBase::shallowCopy(void) const
{
    VariableHeightLayoutManager *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const VariableHeightLayoutManager *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

VariableHeightLayoutManagerBase::VariableHeightLayoutManagerBase(void) :
    Inherited()
{
}

VariableHeightLayoutManagerBase::VariableHeightLayoutManagerBase(const VariableHeightLayoutManagerBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

VariableHeightLayoutManagerBase::~VariableHeightLayoutManagerBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void VariableHeightLayoutManagerBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    VariableHeightLayoutManager *pThis = static_cast<VariableHeightLayoutManager *>(this);

    pThis->execSync(static_cast<VariableHeightLayoutManager *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *VariableHeightLayoutManagerBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    VariableHeightLayoutManager *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const VariableHeightLayoutManager *>(pRefAspect),
                  dynamic_cast<const VariableHeightLayoutManager *>(this));

    return returnValue;
}
#endif

void VariableHeightLayoutManagerBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
