/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala*
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVARIABLEHEIGHTLAYOUTMANAGERFIELDS_H_
#define _OSGVARIABLEHEIGHTLAYOUTMANAGERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OpenSG/OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OpenSG/OSGFieldContainerFields.h"
#include "OpenSG/OSGPointerSField.h"
#include "OpenSG/OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VariableHeightLayoutManager;

OSG_GEN_CONTAINERPTR(VariableHeightLayoutManager);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<VariableHeightLayoutManager *> :
    public FieldTraitsFCPtrBase<VariableHeightLayoutManager *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VariableHeightLayoutManager *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVariableHeightLayoutManagerPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVariableHeightLayoutManagerPtr"; }
};

template<> inline
const Char8 *FieldTraits<VariableHeightLayoutManager *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VariableHeightLayoutManager *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VariableHeightLayoutManager *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VariableHeightLayoutManager *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VariableHeightLayoutManager *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VariableHeightLayoutManager *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VariableHeightLayoutManager *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VariableHeightLayoutManager *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVariableHeightLayoutManagerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<VariableHeightLayoutManager *,
                      RecordedRefCountPolicy  > SFRecVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<VariableHeightLayoutManager *,
                      UnrecordedRefCountPolicy> SFUnrecVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<VariableHeightLayoutManager *,
                      WeakRefCountPolicy      > SFWeakVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<VariableHeightLayoutManager *,
                      NoRefCountPolicy        > SFUncountedVariableHeightLayoutManagerPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<VariableHeightLayoutManager *,
                      RecordedRefCountPolicy  > MFRecVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<VariableHeightLayoutManager *,
                      UnrecordedRefCountPolicy> MFUnrecVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<VariableHeightLayoutManager *,
                      WeakRefCountPolicy      > MFWeakVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<VariableHeightLayoutManager *,
                      NoRefCountPolicy        > MFUncountedVariableHeightLayoutManagerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecVariableHeightLayoutManagerPtr : 
    public PointerSField<VariableHeightLayoutManager *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecVariableHeightLayoutManagerPtr : 
    public PointerSField<VariableHeightLayoutManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakVariableHeightLayoutManagerPtr :
    public PointerSField<VariableHeightLayoutManager *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedVariableHeightLayoutManagerPtr :
    public PointerSField<VariableHeightLayoutManager *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecVariableHeightLayoutManagerPtr :
    public PointerMField<VariableHeightLayoutManager *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecVariableHeightLayoutManagerPtr :
    public PointerMField<VariableHeightLayoutManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakVariableHeightLayoutManagerPtr :
    public PointerMField<VariableHeightLayoutManager *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedVariableHeightLayoutManagerPtr :
    public PointerMField<VariableHeightLayoutManager *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVARIABLEHEIGHTLAYOUTMANAGERFIELDS_H_ */
