/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletSimulationEventDetails!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBulletSimulationEventDetailsBase.h"
#include "OSGBulletSimulationEventDetails.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletSimulationEventDetails
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var UInt32          BulletSimulationEventDetailsBase::_sfNumSteps
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletSimulationEventDetails *>::_type("BulletSimulationEventDetailsPtr", "EventDetailsPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletSimulationEventDetails *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletSimulationEventDetails *,
                           0);


/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletSimulationEventDetailsBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "NumSteps",
        "",
        NumStepsFieldId, NumStepsFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletSimulationEventDetails::editHandleNumSteps),
        static_cast<FieldGetMethodSig >(&BulletSimulationEventDetails::getHandleNumSteps));

    oType.addInitialDesc(pDesc);
}


BulletSimulationEventDetailsBase::TypeObject BulletSimulationEventDetailsBase::_type(
    BulletSimulationEventDetailsBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletSimulationEventDetailsBase::createEmptyLocal),
    BulletSimulationEventDetails::initMethod,
    BulletSimulationEventDetails::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletSimulationEventDetails::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"BulletSimulationEventDetails\"\n"
    "\tparent=\"EventDetails\"\n"
    "    library=\"ContribBullet\"\n"
    "    pointerfieldtypes=\"single\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    isBundle=\"true\"\n"
    "\tsupportUnregisteredCreate=\"true\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    ">\n"
    "\t<Field\n"
    "\t\tname=\"NumSteps\"\n"
    "\t\ttype=\"UInt32\"\n"
    "        category=\"data\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"internal\"\n"
    "\t\taccess=\"protected\"\n"
    "\t\tdefaultValue=\"0\"\n"
    "        publicRead=\"true\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletSimulationEventDetailsBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletSimulationEventDetailsBase::getType(void) const
{
    return _type;
}

UInt32 BulletSimulationEventDetailsBase::getContainerSize(void) const
{
    return sizeof(BulletSimulationEventDetails);
}

/*------------------------- decorator get ------------------------------*/


SFUInt32 *BulletSimulationEventDetailsBase::editSFNumSteps(void)
{
    editSField(NumStepsFieldMask);

    return &_sfNumSteps;
}

const SFUInt32 *BulletSimulationEventDetailsBase::getSFNumSteps(void) const
{
    return &_sfNumSteps;
}






/*------------------------------ access -----------------------------------*/

UInt32 BulletSimulationEventDetailsBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (NumStepsFieldMask & whichField))
    {
        returnValue += _sfNumSteps.getBinSize();
    }

    return returnValue;
}

void BulletSimulationEventDetailsBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (NumStepsFieldMask & whichField))
    {
        _sfNumSteps.copyToBin(pMem);
    }
}

void BulletSimulationEventDetailsBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (NumStepsFieldMask & whichField))
    {
        editSField(NumStepsFieldMask);
        _sfNumSteps.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BulletSimulationEventDetailsTransitPtr BulletSimulationEventDetailsBase::createLocal(BitVector bFlags)
{
    BulletSimulationEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletSimulationEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletSimulationEventDetailsTransitPtr BulletSimulationEventDetailsBase::createDependent(BitVector bFlags)
{
    BulletSimulationEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletSimulationEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletSimulationEventDetailsTransitPtr BulletSimulationEventDetailsBase::create(void)
{
    return createLocal();
}

BulletSimulationEventDetails *BulletSimulationEventDetailsBase::createEmptyLocal(BitVector bFlags)
{
    BulletSimulationEventDetails *returnValue;

    newPtr<BulletSimulationEventDetails>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletSimulationEventDetails *BulletSimulationEventDetailsBase::createEmpty(void)
{
    return createEmptyLocal();
}

BulletSimulationEventDetails *BulletSimulationEventDetailsBase::createUnregistered(void)
{
    BulletSimulationEventDetails *returnValue = new BulletSimulationEventDetails;

#ifdef OSG_MT_CPTR_ASPECT
    returnValue->setupAspectStore();
#endif
    //Do not register with the FieldContainer Factory

    returnValue->onCreate      (      );
    returnValue->onCreateAspect(returnValue);
    
    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();
    
    return returnValue;
}

FieldContainerTransitPtr BulletSimulationEventDetailsBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletSimulationEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletSimulationEventDetails *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletSimulationEventDetailsBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletSimulationEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletSimulationEventDetails *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletSimulationEventDetailsBase::shallowCopy(void) const
{
    return shallowCopyLocal();
}



/*------------------------- constructors ----------------------------------*/

BulletSimulationEventDetailsBase::BulletSimulationEventDetailsBase(void) :
    Inherited(),
    _sfNumSteps               (UInt32(0))
{
}

BulletSimulationEventDetailsBase::BulletSimulationEventDetailsBase(const BulletSimulationEventDetailsBase &source) :
    Inherited(source),
    _sfNumSteps               (source._sfNumSteps               )
{
}


/*-------------------------- destructors ----------------------------------*/

BulletSimulationEventDetailsBase::~BulletSimulationEventDetailsBase(void)
{
}


GetFieldHandlePtr BulletSimulationEventDetailsBase::getHandleNumSteps        (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfNumSteps,
             this->getType().getFieldDesc(NumStepsFieldId),
             const_cast<BulletSimulationEventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletSimulationEventDetailsBase::editHandleNumSteps       (void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfNumSteps,
             this->getType().getFieldDesc(NumStepsFieldId),
             this));


    editSField(NumStepsFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void BulletSimulationEventDetailsBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletSimulationEventDetails *pThis = static_cast<BulletSimulationEventDetails *>(this);

    pThis->execSync(static_cast<BulletSimulationEventDetails *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletSimulationEventDetailsBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletSimulationEventDetails *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletSimulationEventDetails *>(pRefAspect),
                  dynamic_cast<const BulletSimulationEventDetails *>(this));

    return returnValue;
}
#endif

void BulletSimulationEventDetailsBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
