/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETSIMULATIONEVENTDETAILSFIELDS_H_
#define _OSGBULLETSIMULATIONEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletSimulationEventDetails;

OSG_GEN_CONTAINERPTR(BulletSimulationEventDetails);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletSimulationEventDetails *> :
    public FieldTraitsFCPtrBase<BulletSimulationEventDetails *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletSimulationEventDetails *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletSimulationEventDetailsPtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletSimulationEventDetails *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletSimulationEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSimulationEventDetails *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletSimulationEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSimulationEventDetails *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletSimulationEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSimulationEventDetails *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletSimulationEventDetailsPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSimulationEventDetails *,
                      RecordedRefCountPolicy  > SFRecBulletSimulationEventDetailsPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSimulationEventDetails *,
                      UnrecordedRefCountPolicy> SFUnrecBulletSimulationEventDetailsPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSimulationEventDetails *,
                      WeakRefCountPolicy      > SFWeakBulletSimulationEventDetailsPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSimulationEventDetails *,
                      NoRefCountPolicy        > SFUncountedBulletSimulationEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletSimulationEventDetailsPtr : 
    public PointerSField<BulletSimulationEventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletSimulationEventDetailsPtr : 
    public PointerSField<BulletSimulationEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletSimulationEventDetailsPtr :
    public PointerSField<BulletSimulationEventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletSimulationEventDetailsPtr :
    public PointerSField<BulletSimulationEventDetails *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETSIMULATIONEVENTDETAILSFIELDS_H_ */
