/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETCOLLISIONSHAPEFIELDS_H_
#define _OSGBULLETCOLLISIONSHAPEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletCollisionShape;

OSG_GEN_CONTAINERPTR(BulletCollisionShape);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletCollisionShape *> :
    public FieldTraitsFCPtrBase<BulletCollisionShape *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletCollisionShape *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletCollisionShapePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletCollisionShapePtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletCollisionShapePtr"; 
}


/*! \ingroup GrpContribBulletFieldTraits
 */
template <>
struct FieldTraits<BulletCollisionShape *, 1> :
    public FieldTraitsFCPtrBase<BulletCollisionShape *, 1>
{
  private:

  public:
    typedef FieldTraits<BulletCollisionShape *, 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildBulletCollisionShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCollisionShape *, 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildBulletCollisionShapePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletCollisionShape *,
                      RecordedRefCountPolicy  > SFRecBulletCollisionShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletCollisionShape *,
                      UnrecordedRefCountPolicy> SFUnrecBulletCollisionShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletCollisionShape *,
                      WeakRefCountPolicy      > SFWeakBulletCollisionShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletCollisionShape *,
                      NoRefCountPolicy        > SFUncountedBulletCollisionShapePtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletCollisionShape *,
                      RecordedRefCountPolicy  > MFRecBulletCollisionShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletCollisionShape *,
                      UnrecordedRefCountPolicy> MFUnrecBulletCollisionShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletCollisionShape *,
                      WeakRefCountPolicy      > MFWeakBulletCollisionShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletCollisionShape *,
                      NoRefCountPolicy        > MFUncountedBulletCollisionShapePtr;



/*! \ingroup GrpContribBulletFieldSFields */
typedef ChildPointerSField<
          BulletCollisionShape *, 
          UnrecordedRefCountPolicy,
          1             > SFUnrecChildBulletCollisionShapePtr;



#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletCollisionShapePtr : 
    public PointerSField<BulletCollisionShape *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletCollisionShapePtr : 
    public PointerSField<BulletCollisionShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletCollisionShapePtr :
    public PointerSField<BulletCollisionShape *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletCollisionShapePtr :
    public PointerSField<BulletCollisionShape *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletCollisionShapePtr :
    public PointerMField<BulletCollisionShape *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletCollisionShapePtr :
    public PointerMField<BulletCollisionShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletCollisionShapePtr :
    public PointerMField<BulletCollisionShape *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletCollisionShapePtr :
    public PointerMField<BulletCollisionShape *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecChildBulletCollisionShapePtr :
    public ChildPointerSField<
        BulletCollisionShape *, 
        UnrecordedRefCountPolicy,
        1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETCOLLISIONSHAPEFIELDS_H_ */
