/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETSPHERESHAPEFIELDS_H_
#define _OSGBULLETSPHERESHAPEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletSphereShape;

OSG_GEN_CONTAINERPTR(BulletSphereShape);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletSphereShape *> :
    public FieldTraitsFCPtrBase<BulletSphereShape *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletSphereShape *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletSphereShapePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletSphereShapePtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletSphereShape *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletSphereShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSphereShape *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletSphereShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSphereShape *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletSphereShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSphereShape *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletSphereShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSphereShape *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletSphereShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSphereShape *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletSphereShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSphereShape *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletSphereShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSphereShape *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletSphereShapePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSphereShape *,
                      RecordedRefCountPolicy  > SFRecBulletSphereShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSphereShape *,
                      UnrecordedRefCountPolicy> SFUnrecBulletSphereShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSphereShape *,
                      WeakRefCountPolicy      > SFWeakBulletSphereShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSphereShape *,
                      NoRefCountPolicy        > SFUncountedBulletSphereShapePtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSphereShape *,
                      RecordedRefCountPolicy  > MFRecBulletSphereShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSphereShape *,
                      UnrecordedRefCountPolicy> MFUnrecBulletSphereShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSphereShape *,
                      WeakRefCountPolicy      > MFWeakBulletSphereShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSphereShape *,
                      NoRefCountPolicy        > MFUncountedBulletSphereShapePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletSphereShapePtr : 
    public PointerSField<BulletSphereShape *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletSphereShapePtr : 
    public PointerSField<BulletSphereShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletSphereShapePtr :
    public PointerSField<BulletSphereShape *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletSphereShapePtr :
    public PointerSField<BulletSphereShape *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletSphereShapePtr :
    public PointerMField<BulletSphereShape *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletSphereShapePtr :
    public PointerMField<BulletSphereShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletSphereShapePtr :
    public PointerMField<BulletSphereShape *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletSphereShapePtr :
    public PointerMField<BulletSphereShape *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETSPHERESHAPEFIELDS_H_ */
