/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletConeShape!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBulletConeShapeBase.h"
#include "OSGBulletConeShape.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletConeShape
    This core is a wrapper around the bullet btConeShape.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Real32          BulletConeShapeBase::_sfRadius
    
*/

/*! \var Real32          BulletConeShapeBase::_sfHeight
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletConeShape *>::_type("BulletConeShapePtr", "BulletCollisionShapePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletConeShape *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletConeShape *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BulletConeShape *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletConeShapeBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new BridgeSFReal32::Description(
        BridgeSFReal32::getClassType(),
        "Radius",
        "",
        RadiusFieldId, RadiusFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletConeShape::editHandleRadius),
        static_cast<FieldGetMethodSig >(&BulletConeShape::getHandleRadius));

    oType.addInitialDesc(pDesc);

    pDesc = new BridgeSFReal32::Description(
        BridgeSFReal32::getClassType(),
        "Height",
        "",
        HeightFieldId, HeightFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletConeShape::editHandleHeight),
        static_cast<FieldGetMethodSig >(&BulletConeShape::getHandleHeight));

    oType.addInitialDesc(pDesc);
}


BulletConeShapeBase::TypeObject BulletConeShapeBase::_type(
    BulletConeShapeBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletConeShapeBase::createEmptyLocal),
    BulletConeShape::initMethod,
    BulletConeShape::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletConeShape::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BulletConeShape\"\n"
    "    parent=\"BulletCollisionShape\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet btConeShape.\n"
    "    <Field\n"
    "        name=\"Radius\"\n"
    "        type=\"Real32\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        bridge=\"true\"\n"
    "        >\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"Height\"\n"
    "        type=\"Real32\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        bridge=\"true\"\n"
    "        >\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet btConeShape.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletConeShapeBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletConeShapeBase::getType(void) const
{
    return _type;
}

UInt32 BulletConeShapeBase::getContainerSize(void) const
{
    return sizeof(BulletConeShape);
}

/*------------------------- decorator get ------------------------------*/


BridgeSFReal32 *BulletConeShapeBase::editSFRadius(void)
{
    editSField(RadiusFieldMask);

    return &_sfRadius;
}

const BridgeSFReal32 *BulletConeShapeBase::getSFRadius(void) const
{
    return &_sfRadius;
}


BridgeSFReal32 *BulletConeShapeBase::editSFHeight(void)
{
    editSField(HeightFieldMask);

    return &_sfHeight;
}

const BridgeSFReal32 *BulletConeShapeBase::getSFHeight(void) const
{
    return &_sfHeight;
}






/*------------------------------ access -----------------------------------*/

UInt32 BulletConeShapeBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (RadiusFieldMask & whichField))
    {
        returnValue += _sfRadius.getBinSize();
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        returnValue += _sfHeight.getBinSize();
    }

    return returnValue;
}

void BulletConeShapeBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (RadiusFieldMask & whichField))
    {
        _sfRadius.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        _sfHeight.copyToBin(pMem);
    }
}

void BulletConeShapeBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (RadiusFieldMask & whichField))
    {
        editSField(RadiusFieldMask);
        _sfRadius.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        editSField(HeightFieldMask);
        _sfHeight.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BulletConeShapeTransitPtr BulletConeShapeBase::createLocal(BitVector bFlags)
{
    BulletConeShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletConeShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletConeShapeTransitPtr BulletConeShapeBase::createDependent(BitVector bFlags)
{
    BulletConeShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletConeShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletConeShapeTransitPtr BulletConeShapeBase::create(void)
{
    BulletConeShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BulletConeShape>(tmpPtr);
    }

    return fc;
}

BulletConeShape *BulletConeShapeBase::createEmptyLocal(BitVector bFlags)
{
    BulletConeShape *returnValue;

    newPtr<BulletConeShape>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletConeShape *BulletConeShapeBase::createEmpty(void)
{
    BulletConeShape *returnValue;

    newPtr<BulletConeShape>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr BulletConeShapeBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletConeShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletConeShape *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletConeShapeBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletConeShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletConeShape *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletConeShapeBase::shallowCopy(void) const
{
    BulletConeShape *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BulletConeShape *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BulletConeShapeBase::BulletConeShapeBase(void) :
    Inherited(),
    _sfRadius                 (boost::bind(&BulletConeShape::getExternalRadius, static_cast<BulletConeShape*>(this)),boost::bind(&BulletConeShape::setExternalRadius, static_cast<BulletConeShape*>(this), _1)),
    _sfHeight                 (boost::bind(&BulletConeShape::getExternalHeight, static_cast<BulletConeShape*>(this)),boost::bind(&BulletConeShape::setExternalHeight, static_cast<BulletConeShape*>(this), _1))
{
}

BulletConeShapeBase::BulletConeShapeBase(const BulletConeShapeBase &source) :
    Inherited(source),
    _sfRadius                 (boost::bind(&BulletConeShape::getExternalRadius, static_cast<BulletConeShape*>(this)),boost::bind(&BulletConeShape::setExternalRadius, static_cast<BulletConeShape*>(this), _1)),
    _sfHeight                 (boost::bind(&BulletConeShape::getExternalHeight, static_cast<BulletConeShape*>(this)),boost::bind(&BulletConeShape::setExternalHeight, static_cast<BulletConeShape*>(this), _1))
{
}


/*-------------------------- destructors ----------------------------------*/

BulletConeShapeBase::~BulletConeShapeBase(void)
{
}


GetFieldHandlePtr BulletConeShapeBase::getHandleRadius          (void) const
{
    BridgeSFReal32::GetHandlePtr returnValue(
        new  BridgeSFReal32::GetHandle(
             &_sfRadius,
             this->getType().getFieldDesc(RadiusFieldId),
             const_cast<BulletConeShapeBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletConeShapeBase::editHandleRadius         (void)
{
    BridgeSFReal32::EditHandlePtr returnValue(
        new  BridgeSFReal32::EditHandle(
             &_sfRadius,
             this->getType().getFieldDesc(RadiusFieldId),
             this));


    editSField(RadiusFieldMask);

    return returnValue;
}

GetFieldHandlePtr BulletConeShapeBase::getHandleHeight          (void) const
{
    BridgeSFReal32::GetHandlePtr returnValue(
        new  BridgeSFReal32::GetHandle(
             &_sfHeight,
             this->getType().getFieldDesc(HeightFieldId),
             const_cast<BulletConeShapeBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletConeShapeBase::editHandleHeight         (void)
{
    BridgeSFReal32::EditHandlePtr returnValue(
        new  BridgeSFReal32::EditHandle(
             &_sfHeight,
             this->getType().getFieldDesc(HeightFieldId),
             this));


    editSField(HeightFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void BulletConeShapeBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletConeShape *pThis = static_cast<BulletConeShape *>(this);

    pThis->execSync(static_cast<BulletConeShape *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletConeShapeBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletConeShape *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletConeShape *>(pRefAspect),
                  dynamic_cast<const BulletConeShape *>(this));

    return returnValue;
}
#endif

void BulletConeShapeBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
