/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletCapsuleShape!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBulletCapsuleShapeBase.h"
#include "OSGBulletCapsuleShape.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletCapsuleShape
    This core is a wrapper around the bullet btCapsuleShape.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Real32          BulletCapsuleShapeBase::_sfRadius
    
*/

/*! \var Real32          BulletCapsuleShapeBase::_sfHeight
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletCapsuleShape *>::_type("BulletCapsuleShapePtr", "BulletCollisionShapePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletCapsuleShape *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletCapsuleShape *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BulletCapsuleShape *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletCapsuleShapeBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new BridgeSFReal32::Description(
        BridgeSFReal32::getClassType(),
        "Radius",
        "",
        RadiusFieldId, RadiusFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletCapsuleShape::editHandleRadius),
        static_cast<FieldGetMethodSig >(&BulletCapsuleShape::getHandleRadius));

    oType.addInitialDesc(pDesc);

    pDesc = new BridgeSFReal32::Description(
        BridgeSFReal32::getClassType(),
        "Height",
        "",
        HeightFieldId, HeightFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletCapsuleShape::editHandleHeight),
        static_cast<FieldGetMethodSig >(&BulletCapsuleShape::getHandleHeight));

    oType.addInitialDesc(pDesc);
}


BulletCapsuleShapeBase::TypeObject BulletCapsuleShapeBase::_type(
    BulletCapsuleShapeBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletCapsuleShapeBase::createEmptyLocal),
    BulletCapsuleShape::initMethod,
    BulletCapsuleShape::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletCapsuleShape::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BulletCapsuleShape\"\n"
    "    parent=\"BulletCollisionShape\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet btCapsuleShape.\n"
    "    <Field\n"
    "        name=\"Radius\"\n"
    "        type=\"Real32\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        bridge=\"true\"\n"
    "        >\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"Height\"\n"
    "        type=\"Real32\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        bridge=\"true\"\n"
    "        >\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet btCapsuleShape.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletCapsuleShapeBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletCapsuleShapeBase::getType(void) const
{
    return _type;
}

UInt32 BulletCapsuleShapeBase::getContainerSize(void) const
{
    return sizeof(BulletCapsuleShape);
}

/*------------------------- decorator get ------------------------------*/


BridgeSFReal32 *BulletCapsuleShapeBase::editSFRadius(void)
{
    editSField(RadiusFieldMask);

    return &_sfRadius;
}

const BridgeSFReal32 *BulletCapsuleShapeBase::getSFRadius(void) const
{
    return &_sfRadius;
}


BridgeSFReal32 *BulletCapsuleShapeBase::editSFHeight(void)
{
    editSField(HeightFieldMask);

    return &_sfHeight;
}

const BridgeSFReal32 *BulletCapsuleShapeBase::getSFHeight(void) const
{
    return &_sfHeight;
}






/*------------------------------ access -----------------------------------*/

UInt32 BulletCapsuleShapeBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (RadiusFieldMask & whichField))
    {
        returnValue += _sfRadius.getBinSize();
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        returnValue += _sfHeight.getBinSize();
    }

    return returnValue;
}

void BulletCapsuleShapeBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (RadiusFieldMask & whichField))
    {
        _sfRadius.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        _sfHeight.copyToBin(pMem);
    }
}

void BulletCapsuleShapeBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (RadiusFieldMask & whichField))
    {
        editSField(RadiusFieldMask);
        _sfRadius.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        editSField(HeightFieldMask);
        _sfHeight.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BulletCapsuleShapeTransitPtr BulletCapsuleShapeBase::createLocal(BitVector bFlags)
{
    BulletCapsuleShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletCapsuleShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletCapsuleShapeTransitPtr BulletCapsuleShapeBase::createDependent(BitVector bFlags)
{
    BulletCapsuleShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletCapsuleShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletCapsuleShapeTransitPtr BulletCapsuleShapeBase::create(void)
{
    BulletCapsuleShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BulletCapsuleShape>(tmpPtr);
    }

    return fc;
}

BulletCapsuleShape *BulletCapsuleShapeBase::createEmptyLocal(BitVector bFlags)
{
    BulletCapsuleShape *returnValue;

    newPtr<BulletCapsuleShape>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletCapsuleShape *BulletCapsuleShapeBase::createEmpty(void)
{
    BulletCapsuleShape *returnValue;

    newPtr<BulletCapsuleShape>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr BulletCapsuleShapeBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletCapsuleShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletCapsuleShape *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletCapsuleShapeBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletCapsuleShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletCapsuleShape *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletCapsuleShapeBase::shallowCopy(void) const
{
    BulletCapsuleShape *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BulletCapsuleShape *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BulletCapsuleShapeBase::BulletCapsuleShapeBase(void) :
    Inherited(),
    _sfRadius                 (boost::bind(&BulletCapsuleShape::getExternalRadius, static_cast<BulletCapsuleShape*>(this)),boost::bind(&BulletCapsuleShape::setExternalRadius, static_cast<BulletCapsuleShape*>(this), _1)),
    _sfHeight                 (boost::bind(&BulletCapsuleShape::getExternalHeight, static_cast<BulletCapsuleShape*>(this)),boost::bind(&BulletCapsuleShape::setExternalHeight, static_cast<BulletCapsuleShape*>(this), _1))
{
}

BulletCapsuleShapeBase::BulletCapsuleShapeBase(const BulletCapsuleShapeBase &source) :
    Inherited(source),
    _sfRadius                 (boost::bind(&BulletCapsuleShape::getExternalRadius, static_cast<BulletCapsuleShape*>(this)),boost::bind(&BulletCapsuleShape::setExternalRadius, static_cast<BulletCapsuleShape*>(this), _1)),
    _sfHeight                 (boost::bind(&BulletCapsuleShape::getExternalHeight, static_cast<BulletCapsuleShape*>(this)),boost::bind(&BulletCapsuleShape::setExternalHeight, static_cast<BulletCapsuleShape*>(this), _1))
{
}


/*-------------------------- destructors ----------------------------------*/

BulletCapsuleShapeBase::~BulletCapsuleShapeBase(void)
{
}


GetFieldHandlePtr BulletCapsuleShapeBase::getHandleRadius          (void) const
{
    BridgeSFReal32::GetHandlePtr returnValue(
        new  BridgeSFReal32::GetHandle(
             &_sfRadius,
             this->getType().getFieldDesc(RadiusFieldId),
             const_cast<BulletCapsuleShapeBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletCapsuleShapeBase::editHandleRadius         (void)
{
    BridgeSFReal32::EditHandlePtr returnValue(
        new  BridgeSFReal32::EditHandle(
             &_sfRadius,
             this->getType().getFieldDesc(RadiusFieldId),
             this));


    editSField(RadiusFieldMask);

    return returnValue;
}

GetFieldHandlePtr BulletCapsuleShapeBase::getHandleHeight          (void) const
{
    BridgeSFReal32::GetHandlePtr returnValue(
        new  BridgeSFReal32::GetHandle(
             &_sfHeight,
             this->getType().getFieldDesc(HeightFieldId),
             const_cast<BulletCapsuleShapeBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletCapsuleShapeBase::editHandleHeight         (void)
{
    BridgeSFReal32::EditHandlePtr returnValue(
        new  BridgeSFReal32::EditHandle(
             &_sfHeight,
             this->getType().getFieldDesc(HeightFieldId),
             this));


    editSField(HeightFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void BulletCapsuleShapeBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletCapsuleShape *pThis = static_cast<BulletCapsuleShape *>(this);

    pThis->execSync(static_cast<BulletCapsuleShape *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletCapsuleShapeBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletCapsuleShape *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletCapsuleShape *>(pRefAspect),
                  dynamic_cast<const BulletCapsuleShape *>(this));

    return returnValue;
}
#endif

void BulletCapsuleShapeBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
