/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETCAPSULESHAPEFIELDS_H_
#define _OSGBULLETCAPSULESHAPEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletCapsuleShape;

OSG_GEN_CONTAINERPTR(BulletCapsuleShape);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletCapsuleShape *> :
    public FieldTraitsFCPtrBase<BulletCapsuleShape *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletCapsuleShape *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletCapsuleShapePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletCapsuleShapePtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletCapsuleShape *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletCapsuleShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCapsuleShape *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletCapsuleShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCapsuleShape *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletCapsuleShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCapsuleShape *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletCapsuleShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCapsuleShape *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletCapsuleShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCapsuleShape *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletCapsuleShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCapsuleShape *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletCapsuleShapePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletCapsuleShape *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletCapsuleShapePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletCapsuleShape *,
                      RecordedRefCountPolicy  > SFRecBulletCapsuleShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletCapsuleShape *,
                      UnrecordedRefCountPolicy> SFUnrecBulletCapsuleShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletCapsuleShape *,
                      WeakRefCountPolicy      > SFWeakBulletCapsuleShapePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletCapsuleShape *,
                      NoRefCountPolicy        > SFUncountedBulletCapsuleShapePtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletCapsuleShape *,
                      RecordedRefCountPolicy  > MFRecBulletCapsuleShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletCapsuleShape *,
                      UnrecordedRefCountPolicy> MFUnrecBulletCapsuleShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletCapsuleShape *,
                      WeakRefCountPolicy      > MFWeakBulletCapsuleShapePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletCapsuleShape *,
                      NoRefCountPolicy        > MFUncountedBulletCapsuleShapePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletCapsuleShapePtr : 
    public PointerSField<BulletCapsuleShape *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletCapsuleShapePtr : 
    public PointerSField<BulletCapsuleShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletCapsuleShapePtr :
    public PointerSField<BulletCapsuleShape *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletCapsuleShapePtr :
    public PointerSField<BulletCapsuleShape *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletCapsuleShapePtr :
    public PointerMField<BulletCapsuleShape *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletCapsuleShapePtr :
    public PointerMField<BulletCapsuleShape *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletCapsuleShapePtr :
    public PointerMField<BulletCapsuleShape *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletCapsuleShapePtr :
    public PointerMField<BulletCapsuleShape *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETCAPSULESHAPEFIELDS_H_ */
