/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletConvexHullShape!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBulletConvexHullShapeBase.h"
#include "OSGBulletConvexHullShape.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletConvexHullShape
    This core is a wrapper around the bullet btConvexHullShape.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Pnt3f           BulletConvexHullShapeBase::_mfPoints
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletConvexHullShape *>::_type("BulletConvexHullShapePtr", "BulletCollisionShapePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletConvexHullShape *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletConvexHullShape *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BulletConvexHullShape *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletConvexHullShapeBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new MFPnt3f::Description(
        MFPnt3f::getClassType(),
        "Points",
        "",
        PointsFieldId, PointsFieldMask,
        false,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletConvexHullShape::editHandlePoints),
        static_cast<FieldGetMethodSig >(&BulletConvexHullShape::getHandlePoints));

    oType.addInitialDesc(pDesc);
}


BulletConvexHullShapeBase::TypeObject BulletConvexHullShapeBase::_type(
    BulletConvexHullShapeBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletConvexHullShapeBase::createEmptyLocal),
    BulletConvexHullShape::initMethod,
    BulletConvexHullShape::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletConvexHullShape::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BulletConvexHullShape\"\n"
    "    parent=\"BulletCollisionShape\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet btConvexHullShape.\n"
    "    <Field\n"
    "        name=\"Points\"\n"
    "        type=\"Pnt3f\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"multi\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet btConvexHullShape.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletConvexHullShapeBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletConvexHullShapeBase::getType(void) const
{
    return _type;
}

UInt32 BulletConvexHullShapeBase::getContainerSize(void) const
{
    return sizeof(BulletConvexHullShape);
}

/*------------------------- decorator get ------------------------------*/


MFPnt3f *BulletConvexHullShapeBase::editMFPoints(void)
{
    editMField(PointsFieldMask, _mfPoints);

    return &_mfPoints;
}

const MFPnt3f *BulletConvexHullShapeBase::getMFPoints(void) const
{
    return &_mfPoints;
}






/*------------------------------ access -----------------------------------*/

UInt32 BulletConvexHullShapeBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (PointsFieldMask & whichField))
    {
        returnValue += _mfPoints.getBinSize();
    }

    return returnValue;
}

void BulletConvexHullShapeBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (PointsFieldMask & whichField))
    {
        _mfPoints.copyToBin(pMem);
    }
}

void BulletConvexHullShapeBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (PointsFieldMask & whichField))
    {
        editMField(PointsFieldMask, _mfPoints);
        _mfPoints.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BulletConvexHullShapeTransitPtr BulletConvexHullShapeBase::createLocal(BitVector bFlags)
{
    BulletConvexHullShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletConvexHullShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletConvexHullShapeTransitPtr BulletConvexHullShapeBase::createDependent(BitVector bFlags)
{
    BulletConvexHullShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletConvexHullShape>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletConvexHullShapeTransitPtr BulletConvexHullShapeBase::create(void)
{
    BulletConvexHullShapeTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BulletConvexHullShape>(tmpPtr);
    }

    return fc;
}

BulletConvexHullShape *BulletConvexHullShapeBase::createEmptyLocal(BitVector bFlags)
{
    BulletConvexHullShape *returnValue;

    newPtr<BulletConvexHullShape>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletConvexHullShape *BulletConvexHullShapeBase::createEmpty(void)
{
    BulletConvexHullShape *returnValue;

    newPtr<BulletConvexHullShape>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr BulletConvexHullShapeBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletConvexHullShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletConvexHullShape *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletConvexHullShapeBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletConvexHullShape *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletConvexHullShape *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletConvexHullShapeBase::shallowCopy(void) const
{
    BulletConvexHullShape *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BulletConvexHullShape *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BulletConvexHullShapeBase::BulletConvexHullShapeBase(void) :
    Inherited(),
    _mfPoints                 ()
{
}

BulletConvexHullShapeBase::BulletConvexHullShapeBase(const BulletConvexHullShapeBase &source) :
    Inherited(source),
    _mfPoints                 (source._mfPoints                 )
{
}


/*-------------------------- destructors ----------------------------------*/

BulletConvexHullShapeBase::~BulletConvexHullShapeBase(void)
{
}


GetFieldHandlePtr BulletConvexHullShapeBase::getHandlePoints          (void) const
{
    MFPnt3f::GetHandlePtr returnValue(
        new  MFPnt3f::GetHandle(
             &_mfPoints,
             this->getType().getFieldDesc(PointsFieldId),
             const_cast<BulletConvexHullShapeBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletConvexHullShapeBase::editHandlePoints         (void)
{
    MFPnt3f::EditHandlePtr returnValue(
        new  MFPnt3f::EditHandle(
             &_mfPoints,
             this->getType().getFieldDesc(PointsFieldId),
             this));


    editMField(PointsFieldMask, _mfPoints);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void BulletConvexHullShapeBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletConvexHullShape *pThis = static_cast<BulletConvexHullShape *>(this);

    pThis->execSync(static_cast<BulletConvexHullShape *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletConvexHullShapeBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletConvexHullShape *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletConvexHullShape *>(pRefAspect),
                  dynamic_cast<const BulletConvexHullShape *>(this));

    return returnValue;
}
#endif

void BulletConvexHullShapeBase::resolveLinks(void)
{
    Inherited::resolveLinks();

#ifdef OSG_MT_CPTR_ASPECT
    AspectOffsetStore oOffsets;

    _pAspectStore->fillOffsetArray(oOffsets, this);
#endif

#ifdef OSG_MT_CPTR_ASPECT
    _mfPoints.terminateShare(Thread::getCurrentAspect(),
                                      oOffsets);
#endif
}


OSG_END_NAMESPACE
