/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Animator!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGTBAnimatorBase.h"
#include "OSGTBAnimator.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::Animator
    Abstract interface for animating the value of a SingleField or the
    index of some MultiField.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<TBAnimator *>::_type("TBAnimatorPtr", "FieldContainerPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(TBAnimator *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TBAnimator *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TBAnimator *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TBAnimatorBase::classDescInserter(TypeObject &oType)
{
}


TBAnimatorBase::TypeObject TBAnimatorBase::_type(
    TBAnimatorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    NULL,
    TBAnimator::initMethod,
    TBAnimator::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TBAnimator::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"Animator\"\n"
    "\tparent=\"FieldContainer\"\n"
    "    library=\"TBAnimation\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"abstract\"\n"
    "\tsystemcomponent=\"true\"\n"
    "\tparentsystemcomponent=\"true\"\n"
    "\tdecoratable=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "Abstract interface for animating the value of a SingleField or the\n"
    "index of some MultiField.\n"
    "</FieldContainer>\n",
    "Abstract interface for animating the value of a SingleField or the\n"
    "index of some MultiField.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TBAnimatorBase::getType(void)
{
    return _type;
}

const FieldContainerType &TBAnimatorBase::getType(void) const
{
    return _type;
}

UInt32 TBAnimatorBase::getContainerSize(void) const
{
    return sizeof(TBAnimator);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 TBAnimatorBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void TBAnimatorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void TBAnimatorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}



/*------------------------- constructors ----------------------------------*/

TBAnimatorBase::TBAnimatorBase(void) :
    Inherited()
{
}

TBAnimatorBase::TBAnimatorBase(const TBAnimatorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TBAnimatorBase::~TBAnimatorBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void TBAnimatorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TBAnimator *pThis = static_cast<TBAnimator *>(this);

    pThis->execSync(static_cast<TBAnimator *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void TBAnimatorBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
