/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTBANIMATIONFIELDS_H_
#define _OSGTBANIMATIONFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGTBAnimationDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TBAnimation;

OSG_GEN_CONTAINERPTR(TBAnimation);

/*! \ingroup GrpTBAnimationFieldTraits
    \ingroup GrpLibOSGTBAnimation
 */
template <>
struct FieldTraits<TBAnimation *> :
    public FieldTraitsFCPtrBase<TBAnimation *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TBAnimation *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_TBANIMATION_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFAnimationPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFAnimationPtr"; }
};

template<> inline
const Char8 *FieldTraits<TBAnimation *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTBAnimationPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpTBAnimationFieldSFields */
typedef PointerSField<TBAnimation *,
                      RecordedRefCountPolicy  > SFRecTBAnimationPtr;
/*! \ingroup GrpTBAnimationFieldSFields */
typedef PointerSField<TBAnimation *,
                      UnrecordedRefCountPolicy> SFUnrecTBAnimationPtr;
/*! \ingroup GrpTBAnimationFieldSFields */
typedef PointerSField<TBAnimation *,
                      WeakRefCountPolicy      > SFWeakTBAnimationPtr;
/*! \ingroup GrpTBAnimationFieldSFields */
typedef PointerSField<TBAnimation *,
                      NoRefCountPolicy        > SFUncountedTBAnimationPtr;


/*! \ingroup GrpTBAnimationFieldMFields */
typedef PointerMField<TBAnimation *,
                      RecordedRefCountPolicy  > MFRecTBAnimationPtr;
/*! \ingroup GrpTBAnimationFieldMFields */
typedef PointerMField<TBAnimation *,
                      UnrecordedRefCountPolicy> MFUnrecTBAnimationPtr;
/*! \ingroup GrpTBAnimationFieldMFields */
typedef PointerMField<TBAnimation *,
                      WeakRefCountPolicy      > MFWeakTBAnimationPtr;
/*! \ingroup GrpTBAnimationFieldMFields */
typedef PointerMField<TBAnimation *,
                      NoRefCountPolicy        > MFUncountedTBAnimationPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpTBAnimationFieldSFields \ingroup GrpLibOSGTBAnimation */
struct SFRecTBAnimationPtr : 
    public PointerSField<TBAnimation *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpTBAnimationFieldSFields \ingroup GrpLibOSGTBAnimation */
struct SFUnrecTBAnimationPtr : 
    public PointerSField<TBAnimation *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpTBAnimationFieldSFields \ingroup GrpLibOSGTBAnimation */
struct SFWeakTBAnimationPtr :
    public PointerSField<TBAnimation *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpTBAnimationFieldSFields \ingroup GrpLibOSGTBAnimation */
struct SFUncountedTBAnimationPtr :
    public PointerSField<TBAnimation *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpTBAnimationFieldMFields \ingroup GrpLibOSGTBAnimation */
struct MFRecTBAnimationPtr :
    public PointerMField<TBAnimation *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpTBAnimationFieldMFields \ingroup GrpLibOSGTBAnimation */
struct MFUnrecTBAnimationPtr :
    public PointerMField<TBAnimation *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpTBAnimationFieldMFields \ingroup GrpLibOSGTBAnimation */
struct MFWeakTBAnimationPtr :
    public PointerMField<TBAnimation *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpTBAnimationFieldMFields \ingroup GrpLibOSGTBAnimation */
struct MFUncountedTBAnimationPtr :
    public PointerMField<TBAnimation *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGANIMATIONFIELDS_H_ */
