/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPLAINTABLELEAFELEMENTFIELDS_H_
#define _OSGPLAINTABLELEAFELEMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PlainTableLeafElement;

OSG_GEN_CONTAINERPTR(PlainTableLeafElement);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<PlainTableLeafElement *> :
    public FieldTraitsFCPtrBase<PlainTableLeafElement *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PlainTableLeafElement *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPlainTableLeafElementPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPlainTableLeafElementPtr"; }
};

template<> inline
const Char8 *FieldTraits<PlainTableLeafElement *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPlainTableLeafElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableLeafElement *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPlainTableLeafElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableLeafElement *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPlainTableLeafElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableLeafElement *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPlainTableLeafElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableLeafElement *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPlainTableLeafElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableLeafElement *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPlainTableLeafElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableLeafElement *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPlainTableLeafElementPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableLeafElement *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPlainTableLeafElementPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableLeafElement *,
                      RecordedRefCountPolicy  > SFRecPlainTableLeafElementPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableLeafElement *,
                      UnrecordedRefCountPolicy> SFUnrecPlainTableLeafElementPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableLeafElement *,
                      WeakRefCountPolicy      > SFWeakPlainTableLeafElementPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableLeafElement *,
                      NoRefCountPolicy        > SFUncountedPlainTableLeafElementPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableLeafElement *,
                      RecordedRefCountPolicy  > MFRecPlainTableLeafElementPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableLeafElement *,
                      UnrecordedRefCountPolicy> MFUnrecPlainTableLeafElementPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableLeafElement *,
                      WeakRefCountPolicy      > MFWeakPlainTableLeafElementPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableLeafElement *,
                      NoRefCountPolicy        > MFUncountedPlainTableLeafElementPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecPlainTableLeafElementPtr : 
    public PointerSField<PlainTableLeafElement *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecPlainTableLeafElementPtr : 
    public PointerSField<PlainTableLeafElement *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakPlainTableLeafElementPtr :
    public PointerSField<PlainTableLeafElement *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedPlainTableLeafElementPtr :
    public PointerSField<PlainTableLeafElement *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecPlainTableLeafElementPtr :
    public PointerMField<PlainTableLeafElement *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecPlainTableLeafElementPtr :
    public PointerMField<PlainTableLeafElement *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakPlainTableLeafElementPtr :
    public PointerMField<PlainTableLeafElement *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedPlainTableLeafElementPtr :
    public PointerMField<PlainTableLeafElement *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPLAINTABLELEAFELEMENTFIELDS_H_ */
