/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPLAINTABLEFIELDS_H_
#define _OSGPLAINTABLEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PlainTable;

OSG_GEN_CONTAINERPTR(PlainTable);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<PlainTable *> :
    public FieldTraitsFCPtrBase<PlainTable *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PlainTable *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPlainTablePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPlainTablePtr"; }
};

template<> inline
const Char8 *FieldTraits<PlainTable *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPlainTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTable *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPlainTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTable *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPlainTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTable *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPlainTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTable *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPlainTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTable *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPlainTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTable *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPlainTablePtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTable *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPlainTablePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTable *,
                      RecordedRefCountPolicy  > SFRecPlainTablePtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTable *,
                      UnrecordedRefCountPolicy> SFUnrecPlainTablePtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTable *,
                      WeakRefCountPolicy      > SFWeakPlainTablePtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTable *,
                      NoRefCountPolicy        > SFUncountedPlainTablePtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTable *,
                      RecordedRefCountPolicy  > MFRecPlainTablePtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTable *,
                      UnrecordedRefCountPolicy> MFUnrecPlainTablePtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTable *,
                      WeakRefCountPolicy      > MFWeakPlainTablePtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTable *,
                      NoRefCountPolicy        > MFUncountedPlainTablePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecPlainTablePtr : 
    public PointerSField<PlainTable *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecPlainTablePtr : 
    public PointerSField<PlainTable *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakPlainTablePtr :
    public PointerSField<PlainTable *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedPlainTablePtr :
    public PointerSField<PlainTable *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecPlainTablePtr :
    public PointerMField<PlainTable *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecPlainTablePtr :
    public PointerMField<PlainTable *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakPlainTablePtr :
    public PointerMField<PlainTable *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedPlainTablePtr :
    public PointerMField<PlainTable *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPLAINTABLEFIELDS_H_ */
