/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PlainTableLeafElement!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGPlainTableLeafElementBase.h"
#include "OSGPlainTableLeafElement.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::PlainTableLeafElement
    Plain Table Leaf Element
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<PlainTableLeafElement *>::_type("PlainTableLeafElementPtr", "AbstractLeafElementPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(PlainTableLeafElement *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           PlainTableLeafElement *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           PlainTableLeafElement *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void PlainTableLeafElementBase::classDescInserter(TypeObject &oType)
{
}


PlainTableLeafElementBase::TypeObject PlainTableLeafElementBase::_type(
    PlainTableLeafElementBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&PlainTableLeafElementBase::createEmptyLocal),
    PlainTableLeafElement::initMethod,
    PlainTableLeafElement::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&PlainTableLeafElement::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"PlainTableLeafElement\"\n"
    "\tparent=\"AbstractLeafElement\"\n"
    "    library=\"ContribTableDom\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"false\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "Plain Table Leaf Element\n"
    "</FieldContainer>\n"
    "\n"
    "\n",
    "Plain Table Leaf Element\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &PlainTableLeafElementBase::getType(void)
{
    return _type;
}

const FieldContainerType &PlainTableLeafElementBase::getType(void) const
{
    return _type;
}

UInt32 PlainTableLeafElementBase::getContainerSize(void) const
{
    return sizeof(PlainTableLeafElement);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 PlainTableLeafElementBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void PlainTableLeafElementBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void PlainTableLeafElementBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
PlainTableLeafElementTransitPtr PlainTableLeafElementBase::createLocal(BitVector bFlags)
{
    PlainTableLeafElementTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<PlainTableLeafElement>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
PlainTableLeafElementTransitPtr PlainTableLeafElementBase::createDependent(BitVector bFlags)
{
    PlainTableLeafElementTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<PlainTableLeafElement>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
PlainTableLeafElementTransitPtr PlainTableLeafElementBase::create(void)
{
    PlainTableLeafElementTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<PlainTableLeafElement>(tmpPtr);
    }

    return fc;
}

PlainTableLeafElement *PlainTableLeafElementBase::createEmptyLocal(BitVector bFlags)
{
    PlainTableLeafElement *returnValue;

    newPtr<PlainTableLeafElement>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
PlainTableLeafElement *PlainTableLeafElementBase::createEmpty(void)
{
    PlainTableLeafElement *returnValue;

    newPtr<PlainTableLeafElement>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr PlainTableLeafElementBase::shallowCopyLocal(
    BitVector bFlags) const
{
    PlainTableLeafElement *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PlainTableLeafElement *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr PlainTableLeafElementBase::shallowCopyDependent(
    BitVector bFlags) const
{
    PlainTableLeafElement *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PlainTableLeafElement *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr PlainTableLeafElementBase::shallowCopy(void) const
{
    PlainTableLeafElement *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const PlainTableLeafElement *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

PlainTableLeafElementBase::PlainTableLeafElementBase(void) :
    Inherited()
{
}

PlainTableLeafElementBase::PlainTableLeafElementBase(const PlainTableLeafElementBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

PlainTableLeafElementBase::~PlainTableLeafElementBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void PlainTableLeafElementBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    PlainTableLeafElement *pThis = static_cast<PlainTableLeafElement *>(this);

    pThis->execSync(static_cast<PlainTableLeafElement *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *PlainTableLeafElementBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    PlainTableLeafElement *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const PlainTableLeafElement *>(pRefAspect),
                  dynamic_cast<const PlainTableLeafElement *>(this));

    return returnValue;
}
#endif

void PlainTableLeafElementBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
