/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PlainTableBranchElement!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGPlainTableBranchElementBase.h"
#include "OSGPlainTableBranchElement.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::PlainTableBranchElement
    Plain Table Branch Element
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<PlainTableBranchElement *>::_type("PlainTableBranchElementPtr", "AbstractBranchElementPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(PlainTableBranchElement *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           PlainTableBranchElement *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           PlainTableBranchElement *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void PlainTableBranchElementBase::classDescInserter(TypeObject &oType)
{
}


PlainTableBranchElementBase::TypeObject PlainTableBranchElementBase::_type(
    PlainTableBranchElementBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&PlainTableBranchElementBase::createEmptyLocal),
    PlainTableBranchElement::initMethod,
    PlainTableBranchElement::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&PlainTableBranchElement::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"PlainTableBranchElement\"\n"
    "\tparent=\"AbstractBranchElement\"\n"
    "    library=\"ContribTableDom\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"false\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "Plain Table Branch Element\n"
    "</FieldContainer>\n"
    "\n",
    "Plain Table Branch Element\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &PlainTableBranchElementBase::getType(void)
{
    return _type;
}

const FieldContainerType &PlainTableBranchElementBase::getType(void) const
{
    return _type;
}

UInt32 PlainTableBranchElementBase::getContainerSize(void) const
{
    return sizeof(PlainTableBranchElement);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 PlainTableBranchElementBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void PlainTableBranchElementBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void PlainTableBranchElementBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
PlainTableBranchElementTransitPtr PlainTableBranchElementBase::createLocal(BitVector bFlags)
{
    PlainTableBranchElementTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<PlainTableBranchElement>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
PlainTableBranchElementTransitPtr PlainTableBranchElementBase::createDependent(BitVector bFlags)
{
    PlainTableBranchElementTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<PlainTableBranchElement>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
PlainTableBranchElementTransitPtr PlainTableBranchElementBase::create(void)
{
    PlainTableBranchElementTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<PlainTableBranchElement>(tmpPtr);
    }

    return fc;
}

PlainTableBranchElement *PlainTableBranchElementBase::createEmptyLocal(BitVector bFlags)
{
    PlainTableBranchElement *returnValue;

    newPtr<PlainTableBranchElement>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
PlainTableBranchElement *PlainTableBranchElementBase::createEmpty(void)
{
    PlainTableBranchElement *returnValue;

    newPtr<PlainTableBranchElement>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr PlainTableBranchElementBase::shallowCopyLocal(
    BitVector bFlags) const
{
    PlainTableBranchElement *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PlainTableBranchElement *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr PlainTableBranchElementBase::shallowCopyDependent(
    BitVector bFlags) const
{
    PlainTableBranchElement *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PlainTableBranchElement *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr PlainTableBranchElementBase::shallowCopy(void) const
{
    PlainTableBranchElement *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const PlainTableBranchElement *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

PlainTableBranchElementBase::PlainTableBranchElementBase(void) :
    Inherited()
{
}

PlainTableBranchElementBase::PlainTableBranchElementBase(const PlainTableBranchElementBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

PlainTableBranchElementBase::~PlainTableBranchElementBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void PlainTableBranchElementBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    PlainTableBranchElement *pThis = static_cast<PlainTableBranchElement *>(this);

    pThis->execSync(static_cast<PlainTableBranchElement *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *PlainTableBranchElementBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    PlainTableBranchElement *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const PlainTableBranchElement *>(pRefAspect),
                  dynamic_cast<const PlainTableBranchElement *>(this));

    return returnValue;
}
#endif

void PlainTableBranchElementBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
