/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBREAKPOINTGUTTERFIELDS_H_
#define _OSGBREAKPOINTGUTTERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribLuaToolboxDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BreakpointGutter;

OSG_GEN_CONTAINERPTR(BreakpointGutter);

/*! \ingroup GrpContribLuaToolboxFieldTraits
    \ingroup GrpLibOSGContribLuaToolbox
 */
template <>
struct FieldTraits<BreakpointGutter *> :
    public FieldTraitsFCPtrBase<BreakpointGutter *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BreakpointGutter *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBLUATOOLBOX_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBreakpointGutterPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBreakpointGutterPtr"; }
};

template<> inline
const Char8 *FieldTraits<BreakpointGutter *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBreakpointGutterPtr"; 
}

template<> inline
const Char8 *FieldTraits<BreakpointGutter *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBreakpointGutterPtr"; 
}

template<> inline
const Char8 *FieldTraits<BreakpointGutter *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBreakpointGutterPtr"; 
}

template<> inline
const Char8 *FieldTraits<BreakpointGutter *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBreakpointGutterPtr"; 
}

template<> inline
const Char8 *FieldTraits<BreakpointGutter *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBreakpointGutterPtr"; 
}

template<> inline
const Char8 *FieldTraits<BreakpointGutter *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBreakpointGutterPtr"; 
}

template<> inline
const Char8 *FieldTraits<BreakpointGutter *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBreakpointGutterPtr"; 
}

template<> inline
const Char8 *FieldTraits<BreakpointGutter *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBreakpointGutterPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribLuaToolboxFieldSFields */
typedef PointerSField<BreakpointGutter *,
                      RecordedRefCountPolicy  > SFRecBreakpointGutterPtr;
/*! \ingroup GrpContribLuaToolboxFieldSFields */
typedef PointerSField<BreakpointGutter *,
                      UnrecordedRefCountPolicy> SFUnrecBreakpointGutterPtr;
/*! \ingroup GrpContribLuaToolboxFieldSFields */
typedef PointerSField<BreakpointGutter *,
                      WeakRefCountPolicy      > SFWeakBreakpointGutterPtr;
/*! \ingroup GrpContribLuaToolboxFieldSFields */
typedef PointerSField<BreakpointGutter *,
                      NoRefCountPolicy        > SFUncountedBreakpointGutterPtr;


/*! \ingroup GrpContribLuaToolboxFieldMFields */
typedef PointerMField<BreakpointGutter *,
                      RecordedRefCountPolicy  > MFRecBreakpointGutterPtr;
/*! \ingroup GrpContribLuaToolboxFieldMFields */
typedef PointerMField<BreakpointGutter *,
                      UnrecordedRefCountPolicy> MFUnrecBreakpointGutterPtr;
/*! \ingroup GrpContribLuaToolboxFieldMFields */
typedef PointerMField<BreakpointGutter *,
                      WeakRefCountPolicy      > MFWeakBreakpointGutterPtr;
/*! \ingroup GrpContribLuaToolboxFieldMFields */
typedef PointerMField<BreakpointGutter *,
                      NoRefCountPolicy        > MFUncountedBreakpointGutterPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribLuaToolboxFieldSFields \ingroup GrpLibOSGContribLuaToolbox */
struct SFRecBreakpointGutterPtr : 
    public PointerSField<BreakpointGutter *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribLuaToolboxFieldSFields \ingroup GrpLibOSGContribLuaToolbox */
struct SFUnrecBreakpointGutterPtr : 
    public PointerSField<BreakpointGutter *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribLuaToolboxFieldSFields \ingroup GrpLibOSGContribLuaToolbox */
struct SFWeakBreakpointGutterPtr :
    public PointerSField<BreakpointGutter *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribLuaToolboxFieldSFields \ingroup GrpLibOSGContribLuaToolbox */
struct SFUncountedBreakpointGutterPtr :
    public PointerSField<BreakpointGutter *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribLuaToolboxFieldMFields \ingroup GrpLibOSGContribLuaToolbox */
struct MFRecBreakpointGutterPtr :
    public PointerMField<BreakpointGutter *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribLuaToolboxFieldMFields \ingroup GrpLibOSGContribLuaToolbox */
struct MFUnrecBreakpointGutterPtr :
    public PointerMField<BreakpointGutter *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribLuaToolboxFieldMFields \ingroup GrpLibOSGContribLuaToolbox */
struct MFWeakBreakpointGutterPtr :
    public PointerMField<BreakpointGutter *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribLuaToolboxFieldMFields \ingroup GrpLibOSGContribLuaToolbox */
struct MFUncountedBreakpointGutterPtr :
    public PointerMField<BreakpointGutter *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBREAKPOINTGUTTERFIELDS_H_ */
