/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BreakpointGutter
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBREAKPOINTGUTTERBASE_H_
#define _OSGBREAKPOINTGUTTERBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGContribLuaToolboxDef.h"

//#include "OSGBaseTypes.h"

#include "OSGTextAreaGutter.h" // Parent

#include "OSGButtonFields.h"            // FileBreakpointPrototype type

#include "OSGBreakpointGutterFields.h"

OSG_BEGIN_NAMESPACE

class BreakpointGutter;

//! \brief BreakpointGutter Base Class.

class OSG_CONTRIBLUATOOLBOX_DLLMAPPING BreakpointGutterBase : public TextAreaGutter
{
  public:

    typedef TextAreaGutter Inherited;
    typedef TextAreaGutter ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(BreakpointGutter);
    
    

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        FileBreakpointPrototypeFieldId = Inherited::NextFieldId,
        ConditionalBreakpointPrototypeFieldId = FileBreakpointPrototypeFieldId + 1,
        CountBreakpointPrototypeFieldId = ConditionalBreakpointPrototypeFieldId + 1,
        NextFieldId = CountBreakpointPrototypeFieldId + 1
    };

    static const OSG::BitVector FileBreakpointPrototypeFieldMask =
        (TypeTraits<BitVector>::One << FileBreakpointPrototypeFieldId);
    static const OSG::BitVector ConditionalBreakpointPrototypeFieldMask =
        (TypeTraits<BitVector>::One << ConditionalBreakpointPrototypeFieldId);
    static const OSG::BitVector CountBreakpointPrototypeFieldMask =
        (TypeTraits<BitVector>::One << CountBreakpointPrototypeFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef MFButton          MFFileBreakpointPrototypeType;
    typedef MFButton          MFConditionalBreakpointPrototypeType;
    typedef MFButton          MFCountBreakpointPrototypeType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */


                  MFButton            *editMFFileBreakpointPrototype(void);
            const MFButton            *getMFFileBreakpointPrototype (void) const;

                  MFButton            *editMFConditionalBreakpointPrototype(void);
            const MFButton            *getMFConditionalBreakpointPrototype (void) const;

                  MFButton            *editMFCountBreakpointPrototype(void);
            const MFButton            *getMFCountBreakpointPrototype (void) const;


                  Button              &editFileBreakpointPrototype(const UInt32 index);
            const Button              &getFileBreakpointPrototype (const UInt32 index) const;

                  Button              &editConditionalBreakpointPrototype(const UInt32 index);
            const Button              &getConditionalBreakpointPrototype (const UInt32 index) const;

                  Button              &editCountBreakpointPrototype(const UInt32 index);
            const Button              &getCountBreakpointPrototype (const UInt32 index) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  BreakpointGutterTransitPtr  create          (void);
    static  BreakpointGutter           *createEmpty     (void);

    static  BreakpointGutterTransitPtr  createLocal     (
                                               BitVector bFlags = FCLocal::All);

    static  BreakpointGutter            *createEmptyLocal(
                                              BitVector bFlags = FCLocal::All);

    static  BreakpointGutterTransitPtr  createDependent  (BitVector bFlags);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerTransitPtr shallowCopy     (void) const;
    virtual FieldContainerTransitPtr shallowCopyLocal(
                                       BitVector bFlags = FCLocal::All) const;
    virtual FieldContainerTransitPtr shallowCopyDependent(
                                                      BitVector bFlags) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    MFButton          _mfFileBreakpointPrototype;
    MFButton          _mfConditionalBreakpointPrototype;
    MFButton          _mfCountBreakpointPrototype;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    BreakpointGutterBase(void);
    BreakpointGutterBase(const BreakpointGutterBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~BreakpointGutterBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleFileBreakpointPrototype (void) const;
    EditFieldHandlePtr editHandleFileBreakpointPrototype(void);
    GetFieldHandlePtr  getHandleConditionalBreakpointPrototype (void) const;
    EditFieldHandlePtr editHandleConditionalBreakpointPrototype(void);
    GetFieldHandlePtr  getHandleCountBreakpointPrototype (void) const;
    EditFieldHandlePtr editHandleCountBreakpointPrototype(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      BreakpointGutterBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainer *createAspectCopy(
                                    const FieldContainer *pRefAspect) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const BreakpointGutterBase &source);
};

typedef BreakpointGutterBase *BreakpointGutterBaseP;

OSG_END_NAMESPACE

#endif /* _OSGBREAKPOINTGUTTERBASE_H_ */
