/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETDEBUGFOREGROUNDFIELDS_H_
#define _OSGBULLETDEBUGFOREGROUNDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletDebugForeground;

OSG_GEN_CONTAINERPTR(BulletDebugForeground);

/*! \ingroup GrpBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletDebugForeground *> :
    public FieldTraitsFCPtrBase<BulletDebugForeground *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletDebugForeground *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletDebugForegroundPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletDebugForegroundPtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletDebugForeground *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletDebugForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDebugForeground *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletDebugForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDebugForeground *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletDebugForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDebugForeground *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletDebugForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDebugForeground *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletDebugForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDebugForeground *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletDebugForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDebugForeground *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletDebugForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDebugForeground *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletDebugForegroundPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBulletFieldSFields */
typedef PointerSField<BulletDebugForeground *,
                      RecordedRefCountPolicy  > SFRecBulletDebugForegroundPtr;
/*! \ingroup GrpBulletFieldSFields */
typedef PointerSField<BulletDebugForeground *,
                      UnrecordedRefCountPolicy> SFUnrecBulletDebugForegroundPtr;
/*! \ingroup GrpBulletFieldSFields */
typedef PointerSField<BulletDebugForeground *,
                      WeakRefCountPolicy      > SFWeakBulletDebugForegroundPtr;
/*! \ingroup GrpBulletFieldSFields */
typedef PointerSField<BulletDebugForeground *,
                      NoRefCountPolicy        > SFUncountedBulletDebugForegroundPtr;


/*! \ingroup GrpBulletFieldMFields */
typedef PointerMField<BulletDebugForeground *,
                      RecordedRefCountPolicy  > MFRecBulletDebugForegroundPtr;
/*! \ingroup GrpBulletFieldMFields */
typedef PointerMField<BulletDebugForeground *,
                      UnrecordedRefCountPolicy> MFUnrecBulletDebugForegroundPtr;
/*! \ingroup GrpBulletFieldMFields */
typedef PointerMField<BulletDebugForeground *,
                      WeakRefCountPolicy      > MFWeakBulletDebugForegroundPtr;
/*! \ingroup GrpBulletFieldMFields */
typedef PointerMField<BulletDebugForeground *,
                      NoRefCountPolicy        > MFUncountedBulletDebugForegroundPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletDebugForegroundPtr : 
    public PointerSField<BulletDebugForeground *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletDebugForegroundPtr : 
    public PointerSField<BulletDebugForeground *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletDebugForegroundPtr :
    public PointerSField<BulletDebugForeground *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletDebugForegroundPtr :
    public PointerSField<BulletDebugForeground *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletDebugForegroundPtr :
    public PointerMField<BulletDebugForeground *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletDebugForegroundPtr :
    public PointerMField<BulletDebugForeground *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletDebugForegroundPtr :
    public PointerMField<BulletDebugForeground *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletDebugForegroundPtr :
    public PointerMField<BulletDebugForeground *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETDEBUGFOREGROUNDFIELDS_H_ */
