/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletDebugForeground
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETDEBUGFOREGROUNDBASE_H_
#define _OSGBULLETDEBUGFOREGROUNDBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

//#include "OSGBaseTypes.h"

#include "OSGForeground.h" // Parent

#include "OSGBulletCollisionWorldFields.h" // World type
#include "OSGSysFields.h"               // Mode type

#include "OSGBulletDebugForegroundFields.h"

OSG_BEGIN_NAMESPACE

class BulletDebugForeground;

//! \brief BulletDebugForeground Base Class.

class OSG_CONTRIBBULLET_DLLMAPPING BulletDebugForegroundBase : public Foreground
{
  public:

    typedef Foreground Inherited;
    typedef Foreground ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(BulletDebugForeground);
    
    

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        WorldFieldId = Inherited::NextFieldId,
        ModeFieldId = WorldFieldId + 1,
        DrawOccludedFieldId = ModeFieldId + 1,
        OccludedAlphaFieldId = DrawOccludedFieldId + 1,
        LineWidthFieldId = OccludedAlphaFieldId + 1,
        NextFieldId = LineWidthFieldId + 1
    };

    static const OSG::BitVector WorldFieldMask =
        (TypeTraits<BitVector>::One << WorldFieldId);
    static const OSG::BitVector ModeFieldMask =
        (TypeTraits<BitVector>::One << ModeFieldId);
    static const OSG::BitVector DrawOccludedFieldMask =
        (TypeTraits<BitVector>::One << DrawOccludedFieldId);
    static const OSG::BitVector OccludedAlphaFieldMask =
        (TypeTraits<BitVector>::One << OccludedAlphaFieldId);
    static const OSG::BitVector LineWidthFieldMask =
        (TypeTraits<BitVector>::One << LineWidthFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef SFUnrecBulletCollisionWorldPtr SFWorldType;
    typedef SFInt32           SFModeType;
    typedef SFBool            SFDrawOccludedType;
    typedef SFReal32          SFOccludedAlphaType;
    typedef SFReal32          SFLineWidthType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

            const SFUnrecBulletCollisionWorldPtr *getSFWorld          (void) const;
                  SFUnrecBulletCollisionWorldPtr *editSFWorld          (void);

                  SFInt32             *editSFMode           (void);
            const SFInt32             *getSFMode            (void) const;

                  SFBool              *editSFDrawOccluded   (void);
            const SFBool              *getSFDrawOccluded    (void) const;

                  SFReal32            *editSFOccludedAlpha  (void);
            const SFReal32            *getSFOccludedAlpha   (void) const;

                  SFReal32            *editSFLineWidth      (void);
            const SFReal32            *getSFLineWidth       (void) const;


                  BulletCollisionWorld * getWorld          (void) const;

                  Int32               &editMode           (void);
                  Int32                getMode            (void) const;

                  bool                &editDrawOccluded   (void);
                  bool                 getDrawOccluded    (void) const;

                  Real32              &editOccludedAlpha  (void);
                  Real32               getOccludedAlpha   (void) const;

                  Real32              &editLineWidth      (void);
                  Real32               getLineWidth       (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setWorld          (BulletCollisionWorld * const value);
            void setMode           (const Int32 value);
            void setDrawOccluded   (const bool value);
            void setOccludedAlpha  (const Real32 value);
            void setLineWidth      (const Real32 value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  BulletDebugForegroundTransitPtr  create          (void);
    static  BulletDebugForeground           *createEmpty     (void);

    static  BulletDebugForegroundTransitPtr  createLocal     (
                                               BitVector bFlags = FCLocal::All);

    static  BulletDebugForeground            *createEmptyLocal(
                                              BitVector bFlags = FCLocal::All);

    static  BulletDebugForegroundTransitPtr  createDependent  (BitVector bFlags);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerTransitPtr shallowCopy     (void) const;
    virtual FieldContainerTransitPtr shallowCopyLocal(
                                       BitVector bFlags = FCLocal::All) const;
    virtual FieldContainerTransitPtr shallowCopyDependent(
                                                      BitVector bFlags) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFUnrecBulletCollisionWorldPtr _sfWorld;
    SFInt32           _sfMode;
    SFBool            _sfDrawOccluded;
    SFReal32          _sfOccludedAlpha;
    SFReal32          _sfLineWidth;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    BulletDebugForegroundBase(void);
    BulletDebugForegroundBase(const BulletDebugForegroundBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~BulletDebugForegroundBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const BulletDebugForeground *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleWorld           (void) const;
    EditFieldHandlePtr editHandleWorld          (void);
    GetFieldHandlePtr  getHandleMode            (void) const;
    EditFieldHandlePtr editHandleMode           (void);
    GetFieldHandlePtr  getHandleDrawOccluded    (void) const;
    EditFieldHandlePtr editHandleDrawOccluded   (void);
    GetFieldHandlePtr  getHandleOccludedAlpha   (void) const;
    EditFieldHandlePtr editHandleOccludedAlpha  (void);
    GetFieldHandlePtr  getHandleLineWidth       (void) const;
    EditFieldHandlePtr editHandleLineWidth      (void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      BulletDebugForegroundBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainer *createAspectCopy(
                                    const FieldContainer *pRefAspect) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const BulletDebugForegroundBase &source);
};

typedef BulletDebugForegroundBase *BulletDebugForegroundBaseP;

OSG_END_NAMESPACE

#endif /* _OSGBULLETDEBUGFOREGROUNDBASE_H_ */
