/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOLORCHOOSERCOMBOBOXCOMPONENTGENERATORFIELDS_H_
#define _OSGCOLORCHOOSERCOMBOBOXCOMPONENTGENERATORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class ColorChooserComboBoxComponentGenerator;

OSG_GEN_CONTAINERPTR(ColorChooserComboBoxComponentGenerator);

/*! \ingroup GrpContribUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribUserInterface
 */
template <>
struct FieldTraits<ColorChooserComboBoxComponentGenerator *> :
    public FieldTraitsFCPtrBase<ColorChooserComboBoxComponentGenerator *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ColorChooserComboBoxComponentGenerator *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFColorChooserComboBoxComponentGeneratorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFColorChooserComboBoxComponentGeneratorPtr"; }
};

template<> inline
const Char8 *FieldTraits<ColorChooserComboBoxComponentGenerator *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecColorChooserComboBoxComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorChooserComboBoxComponentGenerator *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecColorChooserComboBoxComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorChooserComboBoxComponentGenerator *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakColorChooserComboBoxComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorChooserComboBoxComponentGenerator *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdColorChooserComboBoxComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorChooserComboBoxComponentGenerator *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecColorChooserComboBoxComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorChooserComboBoxComponentGenerator *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecColorChooserComboBoxComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorChooserComboBoxComponentGenerator *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakColorChooserComboBoxComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorChooserComboBoxComponentGenerator *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdColorChooserComboBoxComponentGeneratorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<ColorChooserComboBoxComponentGenerator *,
                      RecordedRefCountPolicy  > SFRecColorChooserComboBoxComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<ColorChooserComboBoxComponentGenerator *,
                      UnrecordedRefCountPolicy> SFUnrecColorChooserComboBoxComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<ColorChooserComboBoxComponentGenerator *,
                      WeakRefCountPolicy      > SFWeakColorChooserComboBoxComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<ColorChooserComboBoxComponentGenerator *,
                      NoRefCountPolicy        > SFUncountedColorChooserComboBoxComponentGeneratorPtr;


/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<ColorChooserComboBoxComponentGenerator *,
                      RecordedRefCountPolicy  > MFRecColorChooserComboBoxComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<ColorChooserComboBoxComponentGenerator *,
                      UnrecordedRefCountPolicy> MFUnrecColorChooserComboBoxComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<ColorChooserComboBoxComponentGenerator *,
                      WeakRefCountPolicy      > MFWeakColorChooserComboBoxComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<ColorChooserComboBoxComponentGenerator *,
                      NoRefCountPolicy        > MFUncountedColorChooserComboBoxComponentGeneratorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFRecColorChooserComboBoxComponentGeneratorPtr : 
    public PointerSField<ColorChooserComboBoxComponentGenerator *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUnrecColorChooserComboBoxComponentGeneratorPtr : 
    public PointerSField<ColorChooserComboBoxComponentGenerator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFWeakColorChooserComboBoxComponentGeneratorPtr :
    public PointerSField<ColorChooserComboBoxComponentGenerator *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUncountedColorChooserComboBoxComponentGeneratorPtr :
    public PointerSField<ColorChooserComboBoxComponentGenerator *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFRecColorChooserComboBoxComponentGeneratorPtr :
    public PointerMField<ColorChooserComboBoxComponentGenerator *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUnrecColorChooserComboBoxComponentGeneratorPtr :
    public PointerMField<ColorChooserComboBoxComponentGenerator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFWeakColorChooserComboBoxComponentGeneratorPtr :
    public PointerMField<ColorChooserComboBoxComponentGenerator *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUncountedColorChooserComboBoxComponentGeneratorPtr :
    public PointerMField<ColorChooserComboBoxComponentGenerator *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOLORCHOOSERCOMBOBOXCOMPONENTGENERATORFIELDS_H_ */
