/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTUREFILTERFIELDS_H_
#define _OSGTEXTUREFILTERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribImageProcessingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TextureFilter;

OSG_GEN_CONTAINERPTR(TextureFilter);

/*! \ingroup GrpContribImageProcessingFieldTraits
    \ingroup GrpLibOSGContribImageProcessing
 */
template <>
struct FieldTraits<TextureFilter *> :
    public FieldTraitsFCPtrBase<TextureFilter *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TextureFilter *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBIMAGEPROCESSING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTextureFilterPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTextureFilterPtr"; }
};

template<> inline
const Char8 *FieldTraits<TextureFilter *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureFilter *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureFilter *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureFilter *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureFilter *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureFilter *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureFilter *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureFilter *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTextureFilterPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribImageProcessingFieldSFields */
typedef PointerSField<TextureFilter *,
                      RecordedRefCountPolicy  > SFRecTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldSFields */
typedef PointerSField<TextureFilter *,
                      UnrecordedRefCountPolicy> SFUnrecTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldSFields */
typedef PointerSField<TextureFilter *,
                      WeakRefCountPolicy      > SFWeakTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldSFields */
typedef PointerSField<TextureFilter *,
                      NoRefCountPolicy        > SFUncountedTextureFilterPtr;


/*! \ingroup GrpContribImageProcessingFieldMFields */
typedef PointerMField<TextureFilter *,
                      RecordedRefCountPolicy  > MFRecTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldMFields */
typedef PointerMField<TextureFilter *,
                      UnrecordedRefCountPolicy> MFUnrecTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldMFields */
typedef PointerMField<TextureFilter *,
                      WeakRefCountPolicy      > MFWeakTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldMFields */
typedef PointerMField<TextureFilter *,
                      NoRefCountPolicy        > MFUncountedTextureFilterPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribImageProcessingFieldSFields \ingroup GrpLibOSGContribImageProcessing */
struct SFRecTextureFilterPtr : 
    public PointerSField<TextureFilter *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribImageProcessingFieldSFields \ingroup GrpLibOSGContribImageProcessing */
struct SFUnrecTextureFilterPtr : 
    public PointerSField<TextureFilter *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribImageProcessingFieldSFields \ingroup GrpLibOSGContribImageProcessing */
struct SFWeakTextureFilterPtr :
    public PointerSField<TextureFilter *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribImageProcessingFieldSFields \ingroup GrpLibOSGContribImageProcessing */
struct SFUncountedTextureFilterPtr :
    public PointerSField<TextureFilter *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribImageProcessingFieldMFields \ingroup GrpLibOSGContribImageProcessing */
struct MFRecTextureFilterPtr :
    public PointerMField<TextureFilter *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribImageProcessingFieldMFields \ingroup GrpLibOSGContribImageProcessing */
struct MFUnrecTextureFilterPtr :
    public PointerMField<TextureFilter *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribImageProcessingFieldMFields \ingroup GrpLibOSGContribImageProcessing */
struct MFWeakTextureFilterPtr :
    public PointerMField<TextureFilter *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribImageProcessingFieldMFields \ingroup GrpLibOSGContribImageProcessing */
struct MFUncountedTextureFilterPtr :
    public PointerMField<TextureFilter *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTUREFILTERFIELDS_H_ */
