/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETDISCRETEDYNAMICSWORLDFIELDS_H_
#define _OSGBULLETDISCRETEDYNAMICSWORLDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletDiscreteDynamicsWorld;

OSG_GEN_CONTAINERPTR(BulletDiscreteDynamicsWorld);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletDiscreteDynamicsWorld *> :
    public FieldTraitsFCPtrBase<BulletDiscreteDynamicsWorld *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletDiscreteDynamicsWorld *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletDiscreteDynamicsWorldPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletDiscreteDynamicsWorldPtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletDiscreteDynamicsWorld *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletDiscreteDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDiscreteDynamicsWorld *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletDiscreteDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDiscreteDynamicsWorld *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletDiscreteDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDiscreteDynamicsWorld *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletDiscreteDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDiscreteDynamicsWorld *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletDiscreteDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDiscreteDynamicsWorld *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletDiscreteDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDiscreteDynamicsWorld *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletDiscreteDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDiscreteDynamicsWorld *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletDiscreteDynamicsWorldPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDiscreteDynamicsWorld *,
                      RecordedRefCountPolicy  > SFRecBulletDiscreteDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDiscreteDynamicsWorld *,
                      UnrecordedRefCountPolicy> SFUnrecBulletDiscreteDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDiscreteDynamicsWorld *,
                      WeakRefCountPolicy      > SFWeakBulletDiscreteDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDiscreteDynamicsWorld *,
                      NoRefCountPolicy        > SFUncountedBulletDiscreteDynamicsWorldPtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDiscreteDynamicsWorld *,
                      RecordedRefCountPolicy  > MFRecBulletDiscreteDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDiscreteDynamicsWorld *,
                      UnrecordedRefCountPolicy> MFUnrecBulletDiscreteDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDiscreteDynamicsWorld *,
                      WeakRefCountPolicy      > MFWeakBulletDiscreteDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDiscreteDynamicsWorld *,
                      NoRefCountPolicy        > MFUncountedBulletDiscreteDynamicsWorldPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletDiscreteDynamicsWorldPtr : 
    public PointerSField<BulletDiscreteDynamicsWorld *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletDiscreteDynamicsWorldPtr : 
    public PointerSField<BulletDiscreteDynamicsWorld *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletDiscreteDynamicsWorldPtr :
    public PointerSField<BulletDiscreteDynamicsWorld *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletDiscreteDynamicsWorldPtr :
    public PointerSField<BulletDiscreteDynamicsWorld *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletDiscreteDynamicsWorldPtr :
    public PointerMField<BulletDiscreteDynamicsWorld *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletDiscreteDynamicsWorldPtr :
    public PointerMField<BulletDiscreteDynamicsWorld *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletDiscreteDynamicsWorldPtr :
    public PointerMField<BulletDiscreteDynamicsWorld *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletDiscreteDynamicsWorldPtr :
    public PointerMField<BulletDiscreteDynamicsWorld *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETDISCRETEDYNAMICSWORLDFIELDS_H_ */
