/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETSOFTRIGIDDYNAMICSWORLDFIELDS_H_
#define _OSGBULLETSOFTRIGIDDYNAMICSWORLDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletSoftRigidDynamicsWorld;

OSG_GEN_CONTAINERPTR(BulletSoftRigidDynamicsWorld);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletSoftRigidDynamicsWorld *> :
    public FieldTraitsFCPtrBase<BulletSoftRigidDynamicsWorld *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletSoftRigidDynamicsWorld *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletSoftRigidDynamicsWorldPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletSoftRigidDynamicsWorldPtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletSoftRigidDynamicsWorld *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletSoftRigidDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftRigidDynamicsWorld *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletSoftRigidDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftRigidDynamicsWorld *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletSoftRigidDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftRigidDynamicsWorld *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletSoftRigidDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftRigidDynamicsWorld *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletSoftRigidDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftRigidDynamicsWorld *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletSoftRigidDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftRigidDynamicsWorld *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletSoftRigidDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftRigidDynamicsWorld *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletSoftRigidDynamicsWorldPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSoftRigidDynamicsWorld *,
                      RecordedRefCountPolicy  > SFRecBulletSoftRigidDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSoftRigidDynamicsWorld *,
                      UnrecordedRefCountPolicy> SFUnrecBulletSoftRigidDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSoftRigidDynamicsWorld *,
                      WeakRefCountPolicy      > SFWeakBulletSoftRigidDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSoftRigidDynamicsWorld *,
                      NoRefCountPolicy        > SFUncountedBulletSoftRigidDynamicsWorldPtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSoftRigidDynamicsWorld *,
                      RecordedRefCountPolicy  > MFRecBulletSoftRigidDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSoftRigidDynamicsWorld *,
                      UnrecordedRefCountPolicy> MFUnrecBulletSoftRigidDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSoftRigidDynamicsWorld *,
                      WeakRefCountPolicy      > MFWeakBulletSoftRigidDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSoftRigidDynamicsWorld *,
                      NoRefCountPolicy        > MFUncountedBulletSoftRigidDynamicsWorldPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletSoftRigidDynamicsWorldPtr : 
    public PointerSField<BulletSoftRigidDynamicsWorld *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletSoftRigidDynamicsWorldPtr : 
    public PointerSField<BulletSoftRigidDynamicsWorld *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletSoftRigidDynamicsWorldPtr :
    public PointerSField<BulletSoftRigidDynamicsWorld *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletSoftRigidDynamicsWorldPtr :
    public PointerSField<BulletSoftRigidDynamicsWorld *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletSoftRigidDynamicsWorldPtr :
    public PointerMField<BulletSoftRigidDynamicsWorld *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletSoftRigidDynamicsWorldPtr :
    public PointerMField<BulletSoftRigidDynamicsWorld *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletSoftRigidDynamicsWorldPtr :
    public PointerMField<BulletSoftRigidDynamicsWorld *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletSoftRigidDynamicsWorldPtr :
    public PointerMField<BulletSoftRigidDynamicsWorld *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETSOFTRIGIDDYNAMICSWORLDFIELDS_H_ */
