/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletDiscreteDynamicsWorld!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBulletDiscreteDynamicsWorldBase.h"
#include "OSGBulletDiscreteDynamicsWorld.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletDiscreteDynamicsWorld
    This core is a wrapper around the bullet btDiscreetDynamicsWorld.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var bool            BulletDiscreteDynamicsWorldBase::_sfSynchronizeAllMotionsStates
    Passthrough value to btDiscreetDynamicsWorld.
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletDiscreteDynamicsWorld *>::_type("BulletDiscreteDynamicsWorldPtr", "BulletDynamicsWorldPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletDiscreteDynamicsWorld *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletDiscreteDynamicsWorld *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BulletDiscreteDynamicsWorld *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletDiscreteDynamicsWorldBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new BridgeSFBool::Description(
        BridgeSFBool::getClassType(),
        "SynchronizeAllMotionsStates",
        "Passthrough value to btDiscreetDynamicsWorld.\n",
        SynchronizeAllMotionsStatesFieldId, SynchronizeAllMotionsStatesFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletDiscreteDynamicsWorld::editHandleSynchronizeAllMotionsStates),
        static_cast<FieldGetMethodSig >(&BulletDiscreteDynamicsWorld::getHandleSynchronizeAllMotionsStates));

    oType.addInitialDesc(pDesc);
}


BulletDiscreteDynamicsWorldBase::TypeObject BulletDiscreteDynamicsWorldBase::_type(
    BulletDiscreteDynamicsWorldBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletDiscreteDynamicsWorldBase::createEmptyLocal),
    BulletDiscreteDynamicsWorld::initMethod,
    BulletDiscreteDynamicsWorld::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletDiscreteDynamicsWorld::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BulletDiscreteDynamicsWorld\"\n"
    "    parent=\"BulletDynamicsWorld\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet btDiscreetDynamicsWorld.\n"
    "    <Field\n"
    "        name=\"SynchronizeAllMotionsStates\"\n"
    "        type=\"bool\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        bridge=\"true\"\n"
    "        >\n"
    "        Passthrough value to btDiscreetDynamicsWorld.\n"
    "    </Field>\n"
    "    <!--<Field-->\n"
    "        <!--name=\"CollisionObject\"-->\n"
    "        <!--type=\"\"-->\n"
    "        <!--category=\"pointer\"-->\n"
    "        <!--cardinality=\"single\"-->\n"
    "        <!--visibility=\"external\"-->\n"
    "        <!--access=\"public\"-->\n"
    "        <!--bridge=\"true\"-->\n"
    "        <!-->-->\n"
    "        <!--Passthrough value to btDiscreetDynamicsWorld.-->\n"
    "    <!--</Field>-->\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet btDiscreetDynamicsWorld.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletDiscreteDynamicsWorldBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletDiscreteDynamicsWorldBase::getType(void) const
{
    return _type;
}

UInt32 BulletDiscreteDynamicsWorldBase::getContainerSize(void) const
{
    return sizeof(BulletDiscreteDynamicsWorld);
}

/*------------------------- decorator get ------------------------------*/


BridgeSFBool *BulletDiscreteDynamicsWorldBase::editSFSynchronizeAllMotionsStates(void)
{
    editSField(SynchronizeAllMotionsStatesFieldMask);

    return &_sfSynchronizeAllMotionsStates;
}

const BridgeSFBool *BulletDiscreteDynamicsWorldBase::getSFSynchronizeAllMotionsStates(void) const
{
    return &_sfSynchronizeAllMotionsStates;
}






/*------------------------------ access -----------------------------------*/

UInt32 BulletDiscreteDynamicsWorldBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (SynchronizeAllMotionsStatesFieldMask & whichField))
    {
        returnValue += _sfSynchronizeAllMotionsStates.getBinSize();
    }

    return returnValue;
}

void BulletDiscreteDynamicsWorldBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (SynchronizeAllMotionsStatesFieldMask & whichField))
    {
        _sfSynchronizeAllMotionsStates.copyToBin(pMem);
    }
}

void BulletDiscreteDynamicsWorldBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (SynchronizeAllMotionsStatesFieldMask & whichField))
    {
        editSField(SynchronizeAllMotionsStatesFieldMask);
        _sfSynchronizeAllMotionsStates.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BulletDiscreteDynamicsWorldTransitPtr BulletDiscreteDynamicsWorldBase::createLocal(BitVector bFlags)
{
    BulletDiscreteDynamicsWorldTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletDiscreteDynamicsWorld>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletDiscreteDynamicsWorldTransitPtr BulletDiscreteDynamicsWorldBase::createDependent(BitVector bFlags)
{
    BulletDiscreteDynamicsWorldTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletDiscreteDynamicsWorld>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletDiscreteDynamicsWorldTransitPtr BulletDiscreteDynamicsWorldBase::create(void)
{
    BulletDiscreteDynamicsWorldTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BulletDiscreteDynamicsWorld>(tmpPtr);
    }

    return fc;
}

BulletDiscreteDynamicsWorld *BulletDiscreteDynamicsWorldBase::createEmptyLocal(BitVector bFlags)
{
    BulletDiscreteDynamicsWorld *returnValue;

    newPtr<BulletDiscreteDynamicsWorld>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletDiscreteDynamicsWorld *BulletDiscreteDynamicsWorldBase::createEmpty(void)
{
    BulletDiscreteDynamicsWorld *returnValue;

    newPtr<BulletDiscreteDynamicsWorld>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr BulletDiscreteDynamicsWorldBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletDiscreteDynamicsWorld *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletDiscreteDynamicsWorld *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletDiscreteDynamicsWorldBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletDiscreteDynamicsWorld *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletDiscreteDynamicsWorld *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletDiscreteDynamicsWorldBase::shallowCopy(void) const
{
    BulletDiscreteDynamicsWorld *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BulletDiscreteDynamicsWorld *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BulletDiscreteDynamicsWorldBase::BulletDiscreteDynamicsWorldBase(void) :
    Inherited(),
    _sfSynchronizeAllMotionsStates(boost::bind(&BulletDiscreteDynamicsWorld::getExternalSynchronizeAllMotionsStates, static_cast<BulletDiscreteDynamicsWorld*>(this)),boost::bind(&BulletDiscreteDynamicsWorld::setExternalSynchronizeAllMotionsStates, static_cast<BulletDiscreteDynamicsWorld*>(this), _1))
{
}

BulletDiscreteDynamicsWorldBase::BulletDiscreteDynamicsWorldBase(const BulletDiscreteDynamicsWorldBase &source) :
    Inherited(source),
    _sfSynchronizeAllMotionsStates(boost::bind(&BulletDiscreteDynamicsWorld::getExternalSynchronizeAllMotionsStates, static_cast<BulletDiscreteDynamicsWorld*>(this)),boost::bind(&BulletDiscreteDynamicsWorld::setExternalSynchronizeAllMotionsStates, static_cast<BulletDiscreteDynamicsWorld*>(this), _1))
{
}


/*-------------------------- destructors ----------------------------------*/

BulletDiscreteDynamicsWorldBase::~BulletDiscreteDynamicsWorldBase(void)
{
}


GetFieldHandlePtr BulletDiscreteDynamicsWorldBase::getHandleSynchronizeAllMotionsStates (void) const
{
    BridgeSFBool::GetHandlePtr returnValue(
        new  BridgeSFBool::GetHandle(
             &_sfSynchronizeAllMotionsStates,
             this->getType().getFieldDesc(SynchronizeAllMotionsStatesFieldId),
             const_cast<BulletDiscreteDynamicsWorldBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletDiscreteDynamicsWorldBase::editHandleSynchronizeAllMotionsStates(void)
{
    BridgeSFBool::EditHandlePtr returnValue(
        new  BridgeSFBool::EditHandle(
             &_sfSynchronizeAllMotionsStates,
             this->getType().getFieldDesc(SynchronizeAllMotionsStatesFieldId),
             this));


    editSField(SynchronizeAllMotionsStatesFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void BulletDiscreteDynamicsWorldBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletDiscreteDynamicsWorld *pThis = static_cast<BulletDiscreteDynamicsWorld *>(this);

    pThis->execSync(static_cast<BulletDiscreteDynamicsWorld *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletDiscreteDynamicsWorldBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletDiscreteDynamicsWorld *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletDiscreteDynamicsWorld *>(pRefAspect),
                  dynamic_cast<const BulletDiscreteDynamicsWorld *>(this));

    return returnValue;
}
#endif

void BulletDiscreteDynamicsWorldBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
