/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETDYNAMICSWORLDFIELDS_H_
#define _OSGBULLETDYNAMICSWORLDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletDynamicsWorld;

OSG_GEN_CONTAINERPTR(BulletDynamicsWorld);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletDynamicsWorld *> :
    public FieldTraitsFCPtrBase<BulletDynamicsWorld *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletDynamicsWorld *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletDynamicsWorldPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletDynamicsWorldPtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletDynamicsWorldPtr"; 
}


/*! \ingroup GrpContribBulletFieldTraits
 */
template <>
struct FieldTraits<BulletDynamicsWorld *, 1> :
    public FieldTraitsFCPtrBase<BulletDynamicsWorld *, 1>
{
  private:

  public:
    typedef FieldTraits<BulletDynamicsWorld *, 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildBulletDynamicsWorldPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDynamicsWorld *, 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildBulletDynamicsWorldPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDynamicsWorld *,
                      RecordedRefCountPolicy  > SFRecBulletDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDynamicsWorld *,
                      UnrecordedRefCountPolicy> SFUnrecBulletDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDynamicsWorld *,
                      WeakRefCountPolicy      > SFWeakBulletDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDynamicsWorld *,
                      NoRefCountPolicy        > SFUncountedBulletDynamicsWorldPtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDynamicsWorld *,
                      RecordedRefCountPolicy  > MFRecBulletDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDynamicsWorld *,
                      UnrecordedRefCountPolicy> MFUnrecBulletDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDynamicsWorld *,
                      WeakRefCountPolicy      > MFWeakBulletDynamicsWorldPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDynamicsWorld *,
                      NoRefCountPolicy        > MFUncountedBulletDynamicsWorldPtr;



/*! \ingroup GrpContribBulletFieldSFields */
typedef ChildPointerSField<
          BulletDynamicsWorld *, 
          UnrecordedRefCountPolicy,
          1             > SFUnrecChildBulletDynamicsWorldPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletDynamicsWorldPtr : 
    public PointerSField<BulletDynamicsWorld *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletDynamicsWorldPtr : 
    public PointerSField<BulletDynamicsWorld *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletDynamicsWorldPtr :
    public PointerSField<BulletDynamicsWorld *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletDynamicsWorldPtr :
    public PointerSField<BulletDynamicsWorld *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletDynamicsWorldPtr :
    public PointerMField<BulletDynamicsWorld *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletDynamicsWorldPtr :
    public PointerMField<BulletDynamicsWorld *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletDynamicsWorldPtr :
    public PointerMField<BulletDynamicsWorld *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletDynamicsWorldPtr :
    public PointerMField<BulletDynamicsWorld *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecChildBulletDynamicsWorldPtr :
    public ChildPointerSField<
        BulletDynamicsWorld *, 
        UnrecordedRefCountPolicy,
        1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETDYNAMICSWORLDFIELDS_H_ */
