/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BulletSoftRigidDynamicsWorld!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBulletSoftRigidDynamicsWorldBase.h"
#include "OSGBulletSoftRigidDynamicsWorld.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BulletSoftRigidDynamicsWorld
    This core is a wrapper around the bullet btSoftRigidDynamicsWorld.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Int32           BulletSoftRigidDynamicsWorldBase::_sfDrawFlags
    Passthrough value to btSoftRigidDynamicsWorld.
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BulletSoftRigidDynamicsWorld *>::_type("BulletSoftRigidDynamicsWorldPtr", "BulletDiscreteDynamicsWorldPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BulletSoftRigidDynamicsWorld *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BulletSoftRigidDynamicsWorld *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BulletSoftRigidDynamicsWorld *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BulletSoftRigidDynamicsWorldBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new BridgeSFInt32::Description(
        BridgeSFInt32::getClassType(),
        "DrawFlags",
        "Passthrough value to btSoftRigidDynamicsWorld.\n",
        DrawFlagsFieldId, DrawFlagsFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BulletSoftRigidDynamicsWorld::editHandleDrawFlags),
        static_cast<FieldGetMethodSig >(&BulletSoftRigidDynamicsWorld::getHandleDrawFlags));

    oType.addInitialDesc(pDesc);
}


BulletSoftRigidDynamicsWorldBase::TypeObject BulletSoftRigidDynamicsWorldBase::_type(
    BulletSoftRigidDynamicsWorldBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BulletSoftRigidDynamicsWorldBase::createEmptyLocal),
    BulletSoftRigidDynamicsWorld::initMethod,
    BulletSoftRigidDynamicsWorld::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BulletSoftRigidDynamicsWorld::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BulletSoftRigidDynamicsWorld\"\n"
    "    parent=\"BulletDiscreteDynamicsWorld\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet btSoftRigidDynamicsWorld.\n"
    "    <Field\n"
    "        name=\"DrawFlags\"\n"
    "        type=\"Int32\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        bridge=\"true\"\n"
    "        >\n"
    "        Passthrough value to btSoftRigidDynamicsWorld.\n"
    "    </Field>\n"
    "    <!--<Field-->\n"
    "        <!--name=\"SoftBody\"-->\n"
    "        <!--type=\"\"-->\n"
    "        <!--category=\"pointer\"-->\n"
    "        <!--cardinality=\"single\"-->\n"
    "        <!--visibility=\"external\"-->\n"
    "        <!--access=\"public\"-->\n"
    "        <!--bridge=\"true\"-->\n"
    "        <!-->-->\n"
    "        <!--Passthrough value to btDiscreetDynamicsWorld.-->\n"
    "    <!--</Field>-->\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet btSoftRigidDynamicsWorld.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BulletSoftRigidDynamicsWorldBase::getType(void)
{
    return _type;
}

const FieldContainerType &BulletSoftRigidDynamicsWorldBase::getType(void) const
{
    return _type;
}

UInt32 BulletSoftRigidDynamicsWorldBase::getContainerSize(void) const
{
    return sizeof(BulletSoftRigidDynamicsWorld);
}

/*------------------------- decorator get ------------------------------*/


BridgeSFInt32 *BulletSoftRigidDynamicsWorldBase::editSFDrawFlags(void)
{
    editSField(DrawFlagsFieldMask);

    return &_sfDrawFlags;
}

const BridgeSFInt32 *BulletSoftRigidDynamicsWorldBase::getSFDrawFlags(void) const
{
    return &_sfDrawFlags;
}






/*------------------------------ access -----------------------------------*/

UInt32 BulletSoftRigidDynamicsWorldBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (DrawFlagsFieldMask & whichField))
    {
        returnValue += _sfDrawFlags.getBinSize();
    }

    return returnValue;
}

void BulletSoftRigidDynamicsWorldBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (DrawFlagsFieldMask & whichField))
    {
        _sfDrawFlags.copyToBin(pMem);
    }
}

void BulletSoftRigidDynamicsWorldBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (DrawFlagsFieldMask & whichField))
    {
        editSField(DrawFlagsFieldMask);
        _sfDrawFlags.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BulletSoftRigidDynamicsWorldTransitPtr BulletSoftRigidDynamicsWorldBase::createLocal(BitVector bFlags)
{
    BulletSoftRigidDynamicsWorldTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BulletSoftRigidDynamicsWorld>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BulletSoftRigidDynamicsWorldTransitPtr BulletSoftRigidDynamicsWorldBase::createDependent(BitVector bFlags)
{
    BulletSoftRigidDynamicsWorldTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BulletSoftRigidDynamicsWorld>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BulletSoftRigidDynamicsWorldTransitPtr BulletSoftRigidDynamicsWorldBase::create(void)
{
    BulletSoftRigidDynamicsWorldTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BulletSoftRigidDynamicsWorld>(tmpPtr);
    }

    return fc;
}

BulletSoftRigidDynamicsWorld *BulletSoftRigidDynamicsWorldBase::createEmptyLocal(BitVector bFlags)
{
    BulletSoftRigidDynamicsWorld *returnValue;

    newPtr<BulletSoftRigidDynamicsWorld>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BulletSoftRigidDynamicsWorld *BulletSoftRigidDynamicsWorldBase::createEmpty(void)
{
    BulletSoftRigidDynamicsWorld *returnValue;

    newPtr<BulletSoftRigidDynamicsWorld>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr BulletSoftRigidDynamicsWorldBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BulletSoftRigidDynamicsWorld *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletSoftRigidDynamicsWorld *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletSoftRigidDynamicsWorldBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BulletSoftRigidDynamicsWorld *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BulletSoftRigidDynamicsWorld *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BulletSoftRigidDynamicsWorldBase::shallowCopy(void) const
{
    BulletSoftRigidDynamicsWorld *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BulletSoftRigidDynamicsWorld *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BulletSoftRigidDynamicsWorldBase::BulletSoftRigidDynamicsWorldBase(void) :
    Inherited(),
    _sfDrawFlags              (boost::bind(&BulletSoftRigidDynamicsWorld::getExternalDrawFlags, static_cast<BulletSoftRigidDynamicsWorld*>(this)),boost::bind(&BulletSoftRigidDynamicsWorld::setExternalDrawFlags, static_cast<BulletSoftRigidDynamicsWorld*>(this), _1))
{
}

BulletSoftRigidDynamicsWorldBase::BulletSoftRigidDynamicsWorldBase(const BulletSoftRigidDynamicsWorldBase &source) :
    Inherited(source),
    _sfDrawFlags              (boost::bind(&BulletSoftRigidDynamicsWorld::getExternalDrawFlags, static_cast<BulletSoftRigidDynamicsWorld*>(this)),boost::bind(&BulletSoftRigidDynamicsWorld::setExternalDrawFlags, static_cast<BulletSoftRigidDynamicsWorld*>(this), _1))
{
}


/*-------------------------- destructors ----------------------------------*/

BulletSoftRigidDynamicsWorldBase::~BulletSoftRigidDynamicsWorldBase(void)
{
}


GetFieldHandlePtr BulletSoftRigidDynamicsWorldBase::getHandleDrawFlags       (void) const
{
    BridgeSFInt32::GetHandlePtr returnValue(
        new  BridgeSFInt32::GetHandle(
             &_sfDrawFlags,
             this->getType().getFieldDesc(DrawFlagsFieldId),
             const_cast<BulletSoftRigidDynamicsWorldBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BulletSoftRigidDynamicsWorldBase::editHandleDrawFlags      (void)
{
    BridgeSFInt32::EditHandlePtr returnValue(
        new  BridgeSFInt32::EditHandle(
             &_sfDrawFlags,
             this->getType().getFieldDesc(DrawFlagsFieldId),
             this));


    editSField(DrawFlagsFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void BulletSoftRigidDynamicsWorldBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BulletSoftRigidDynamicsWorld *pThis = static_cast<BulletSoftRigidDynamicsWorld *>(this);

    pThis->execSync(static_cast<BulletSoftRigidDynamicsWorld *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BulletSoftRigidDynamicsWorldBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BulletSoftRigidDynamicsWorld *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BulletSoftRigidDynamicsWorld *>(pRefAspect),
                  dynamic_cast<const BulletSoftRigidDynamicsWorld *>(this));

    return returnValue;
}
#endif

void BulletSoftRigidDynamicsWorldBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
