/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLET32BITAXISSWEEP3FIELDS_H_
#define _OSGBULLET32BITAXISSWEEP3FIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class Bullet32BitAxisSweep3;

OSG_GEN_CONTAINERPTR(Bullet32BitAxisSweep3);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<Bullet32BitAxisSweep3 *> :
    public FieldTraitsFCPtrBase<Bullet32BitAxisSweep3 *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<Bullet32BitAxisSweep3 *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBullet32BitAxisSweep3Ptr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBullet32BitAxisSweep3Ptr"; }
};

template<> inline
const Char8 *FieldTraits<Bullet32BitAxisSweep3 *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBullet32BitAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<Bullet32BitAxisSweep3 *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBullet32BitAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<Bullet32BitAxisSweep3 *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBullet32BitAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<Bullet32BitAxisSweep3 *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBullet32BitAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<Bullet32BitAxisSweep3 *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBullet32BitAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<Bullet32BitAxisSweep3 *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBullet32BitAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<Bullet32BitAxisSweep3 *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBullet32BitAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<Bullet32BitAxisSweep3 *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBullet32BitAxisSweep3Ptr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<Bullet32BitAxisSweep3 *,
                      RecordedRefCountPolicy  > SFRecBullet32BitAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<Bullet32BitAxisSweep3 *,
                      UnrecordedRefCountPolicy> SFUnrecBullet32BitAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<Bullet32BitAxisSweep3 *,
                      WeakRefCountPolicy      > SFWeakBullet32BitAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<Bullet32BitAxisSweep3 *,
                      NoRefCountPolicy        > SFUncountedBullet32BitAxisSweep3Ptr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<Bullet32BitAxisSweep3 *,
                      RecordedRefCountPolicy  > MFRecBullet32BitAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<Bullet32BitAxisSweep3 *,
                      UnrecordedRefCountPolicy> MFUnrecBullet32BitAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<Bullet32BitAxisSweep3 *,
                      WeakRefCountPolicy      > MFWeakBullet32BitAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<Bullet32BitAxisSweep3 *,
                      NoRefCountPolicy        > MFUncountedBullet32BitAxisSweep3Ptr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBullet32BitAxisSweep3Ptr : 
    public PointerSField<Bullet32BitAxisSweep3 *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBullet32BitAxisSweep3Ptr : 
    public PointerSField<Bullet32BitAxisSweep3 *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBullet32BitAxisSweep3Ptr :
    public PointerSField<Bullet32BitAxisSweep3 *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBullet32BitAxisSweep3Ptr :
    public PointerSField<Bullet32BitAxisSweep3 *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBullet32BitAxisSweep3Ptr :
    public PointerMField<Bullet32BitAxisSweep3 *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBullet32BitAxisSweep3Ptr :
    public PointerMField<Bullet32BitAxisSweep3 *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBullet32BitAxisSweep3Ptr :
    public PointerMField<Bullet32BitAxisSweep3 *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBullet32BitAxisSweep3Ptr :
    public PointerMField<Bullet32BitAxisSweep3 *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLET32BITAXISSWEEP3FIELDS_H_ */
