/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETDBVTBROADPHASEFIELDS_H_
#define _OSGBULLETDBVTBROADPHASEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletDbvtBroadphase;

OSG_GEN_CONTAINERPTR(BulletDbvtBroadphase);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletDbvtBroadphase *> :
    public FieldTraitsFCPtrBase<BulletDbvtBroadphase *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletDbvtBroadphase *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletDbvtBroadphasePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletDbvtBroadphasePtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletDbvtBroadphase *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletDbvtBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDbvtBroadphase *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletDbvtBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDbvtBroadphase *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletDbvtBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDbvtBroadphase *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletDbvtBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDbvtBroadphase *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletDbvtBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDbvtBroadphase *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletDbvtBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDbvtBroadphase *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletDbvtBroadphasePtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletDbvtBroadphase *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletDbvtBroadphasePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDbvtBroadphase *,
                      RecordedRefCountPolicy  > SFRecBulletDbvtBroadphasePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDbvtBroadphase *,
                      UnrecordedRefCountPolicy> SFUnrecBulletDbvtBroadphasePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDbvtBroadphase *,
                      WeakRefCountPolicy      > SFWeakBulletDbvtBroadphasePtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletDbvtBroadphase *,
                      NoRefCountPolicy        > SFUncountedBulletDbvtBroadphasePtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDbvtBroadphase *,
                      RecordedRefCountPolicy  > MFRecBulletDbvtBroadphasePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDbvtBroadphase *,
                      UnrecordedRefCountPolicy> MFUnrecBulletDbvtBroadphasePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDbvtBroadphase *,
                      WeakRefCountPolicy      > MFWeakBulletDbvtBroadphasePtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletDbvtBroadphase *,
                      NoRefCountPolicy        > MFUncountedBulletDbvtBroadphasePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletDbvtBroadphasePtr : 
    public PointerSField<BulletDbvtBroadphase *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletDbvtBroadphasePtr : 
    public PointerSField<BulletDbvtBroadphase *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletDbvtBroadphasePtr :
    public PointerSField<BulletDbvtBroadphase *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletDbvtBroadphasePtr :
    public PointerSField<BulletDbvtBroadphase *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletDbvtBroadphasePtr :
    public PointerMField<BulletDbvtBroadphase *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletDbvtBroadphasePtr :
    public PointerMField<BulletDbvtBroadphase *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletDbvtBroadphasePtr :
    public PointerMField<BulletDbvtBroadphase *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletDbvtBroadphasePtr :
    public PointerMField<BulletDbvtBroadphase *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETDBVTBROADPHASEFIELDS_H_ */
