/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Bullet32BitAxisSweep3!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBullet32BitAxisSweep3Base.h"
#include "OSGBullet32BitAxisSweep3.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::Bullet32BitAxisSweep3
    This core is a wrapper around the bullet bt32BitAxisSweep3.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<Bullet32BitAxisSweep3 *>::_type("Bullet32BitAxisSweep3Ptr", "BulletBroadphaseInterfacePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(Bullet32BitAxisSweep3 *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           Bullet32BitAxisSweep3 *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           Bullet32BitAxisSweep3 *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void Bullet32BitAxisSweep3Base::classDescInserter(TypeObject &oType)
{
}


Bullet32BitAxisSweep3Base::TypeObject Bullet32BitAxisSweep3Base::_type(
    Bullet32BitAxisSweep3Base::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&Bullet32BitAxisSweep3Base::createEmptyLocal),
    Bullet32BitAxisSweep3::initMethod,
    Bullet32BitAxisSweep3::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&Bullet32BitAxisSweep3::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"Bullet32BitAxisSweep3\"\n"
    "    parent=\"BulletBroadphaseInterface\"\n"
    "    library=\"ContribBullet\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    >\n"
    "    This core is a wrapper around the bullet bt32BitAxisSweep3.\n"
    "</FieldContainer>\n",
    "This core is a wrapper around the bullet bt32BitAxisSweep3.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &Bullet32BitAxisSweep3Base::getType(void)
{
    return _type;
}

const FieldContainerType &Bullet32BitAxisSweep3Base::getType(void) const
{
    return _type;
}

UInt32 Bullet32BitAxisSweep3Base::getContainerSize(void) const
{
    return sizeof(Bullet32BitAxisSweep3);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 Bullet32BitAxisSweep3Base::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void Bullet32BitAxisSweep3Base::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void Bullet32BitAxisSweep3Base::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
Bullet32BitAxisSweep3TransitPtr Bullet32BitAxisSweep3Base::createLocal(BitVector bFlags)
{
    Bullet32BitAxisSweep3TransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<Bullet32BitAxisSweep3>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
Bullet32BitAxisSweep3TransitPtr Bullet32BitAxisSweep3Base::createDependent(BitVector bFlags)
{
    Bullet32BitAxisSweep3TransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<Bullet32BitAxisSweep3>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
Bullet32BitAxisSweep3TransitPtr Bullet32BitAxisSweep3Base::create(void)
{
    Bullet32BitAxisSweep3TransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<Bullet32BitAxisSweep3>(tmpPtr);
    }

    return fc;
}

Bullet32BitAxisSweep3 *Bullet32BitAxisSweep3Base::createEmptyLocal(BitVector bFlags)
{
    Bullet32BitAxisSweep3 *returnValue;

    newPtr<Bullet32BitAxisSweep3>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
Bullet32BitAxisSweep3 *Bullet32BitAxisSweep3Base::createEmpty(void)
{
    Bullet32BitAxisSweep3 *returnValue;

    newPtr<Bullet32BitAxisSweep3>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr Bullet32BitAxisSweep3Base::shallowCopyLocal(
    BitVector bFlags) const
{
    Bullet32BitAxisSweep3 *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const Bullet32BitAxisSweep3 *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr Bullet32BitAxisSweep3Base::shallowCopyDependent(
    BitVector bFlags) const
{
    Bullet32BitAxisSweep3 *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const Bullet32BitAxisSweep3 *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr Bullet32BitAxisSweep3Base::shallowCopy(void) const
{
    Bullet32BitAxisSweep3 *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const Bullet32BitAxisSweep3 *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

Bullet32BitAxisSweep3Base::Bullet32BitAxisSweep3Base(void) :
    Inherited()
{
}

Bullet32BitAxisSweep3Base::Bullet32BitAxisSweep3Base(const Bullet32BitAxisSweep3Base &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

Bullet32BitAxisSweep3Base::~Bullet32BitAxisSweep3Base(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void Bullet32BitAxisSweep3Base::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    Bullet32BitAxisSweep3 *pThis = static_cast<Bullet32BitAxisSweep3 *>(this);

    pThis->execSync(static_cast<Bullet32BitAxisSweep3 *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *Bullet32BitAxisSweep3Base::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    Bullet32BitAxisSweep3 *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const Bullet32BitAxisSweep3 *>(pRefAspect),
                  dynamic_cast<const Bullet32BitAxisSweep3 *>(this));

    return returnValue;
}
#endif

void Bullet32BitAxisSweep3Base::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
