/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETAXISSWEEP3FIELDS_H_
#define _OSGBULLETAXISSWEEP3FIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletAxisSweep3;

OSG_GEN_CONTAINERPTR(BulletAxisSweep3);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletAxisSweep3 *> :
    public FieldTraitsFCPtrBase<BulletAxisSweep3 *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletAxisSweep3 *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletAxisSweep3Ptr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletAxisSweep3Ptr"; }
};

template<> inline
const Char8 *FieldTraits<BulletAxisSweep3 *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<BulletAxisSweep3 *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<BulletAxisSweep3 *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<BulletAxisSweep3 *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<BulletAxisSweep3 *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<BulletAxisSweep3 *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<BulletAxisSweep3 *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletAxisSweep3Ptr"; 
}

template<> inline
const Char8 *FieldTraits<BulletAxisSweep3 *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletAxisSweep3Ptr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletAxisSweep3 *,
                      RecordedRefCountPolicy  > SFRecBulletAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletAxisSweep3 *,
                      UnrecordedRefCountPolicy> SFUnrecBulletAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletAxisSweep3 *,
                      WeakRefCountPolicy      > SFWeakBulletAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletAxisSweep3 *,
                      NoRefCountPolicy        > SFUncountedBulletAxisSweep3Ptr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletAxisSweep3 *,
                      RecordedRefCountPolicy  > MFRecBulletAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletAxisSweep3 *,
                      UnrecordedRefCountPolicy> MFUnrecBulletAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletAxisSweep3 *,
                      WeakRefCountPolicy      > MFWeakBulletAxisSweep3Ptr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletAxisSweep3 *,
                      NoRefCountPolicy        > MFUncountedBulletAxisSweep3Ptr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletAxisSweep3Ptr : 
    public PointerSField<BulletAxisSweep3 *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletAxisSweep3Ptr : 
    public PointerSField<BulletAxisSweep3 *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletAxisSweep3Ptr :
    public PointerSField<BulletAxisSweep3 *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletAxisSweep3Ptr :
    public PointerSField<BulletAxisSweep3 *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletAxisSweep3Ptr :
    public PointerMField<BulletAxisSweep3 *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletAxisSweep3Ptr :
    public PointerMField<BulletAxisSweep3 *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletAxisSweep3Ptr :
    public PointerMField<BulletAxisSweep3 *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletAxisSweep3Ptr :
    public PointerMField<BulletAxisSweep3 *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETAXISSWEEP3FIELDS_H_ */
