/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSHADERTEXTUREFILTERFIELDS_H_
#define _OSGSHADERTEXTUREFILTERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribImageProcessingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class ShaderTextureFilter;

OSG_GEN_CONTAINERPTR(ShaderTextureFilter);

/*! \ingroup GrpContribImageProcessingFieldTraits
    \ingroup GrpLibOSGContribImageProcessing
 */
template <>
struct FieldTraits<ShaderTextureFilter *> :
    public FieldTraitsFCPtrBase<ShaderTextureFilter *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ShaderTextureFilter *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBIMAGEPROCESSING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFShaderTextureFilterPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFShaderTextureFilterPtr"; }
};

template<> inline
const Char8 *FieldTraits<ShaderTextureFilter *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecShaderTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderTextureFilter *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecShaderTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderTextureFilter *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakShaderTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderTextureFilter *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdShaderTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderTextureFilter *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecShaderTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderTextureFilter *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecShaderTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderTextureFilter *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakShaderTextureFilterPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderTextureFilter *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdShaderTextureFilterPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribImageProcessingFieldSFields */
typedef PointerSField<ShaderTextureFilter *,
                      RecordedRefCountPolicy  > SFRecShaderTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldSFields */
typedef PointerSField<ShaderTextureFilter *,
                      UnrecordedRefCountPolicy> SFUnrecShaderTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldSFields */
typedef PointerSField<ShaderTextureFilter *,
                      WeakRefCountPolicy      > SFWeakShaderTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldSFields */
typedef PointerSField<ShaderTextureFilter *,
                      NoRefCountPolicy        > SFUncountedShaderTextureFilterPtr;


/*! \ingroup GrpContribImageProcessingFieldMFields */
typedef PointerMField<ShaderTextureFilter *,
                      RecordedRefCountPolicy  > MFRecShaderTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldMFields */
typedef PointerMField<ShaderTextureFilter *,
                      UnrecordedRefCountPolicy> MFUnrecShaderTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldMFields */
typedef PointerMField<ShaderTextureFilter *,
                      WeakRefCountPolicy      > MFWeakShaderTextureFilterPtr;
/*! \ingroup GrpContribImageProcessingFieldMFields */
typedef PointerMField<ShaderTextureFilter *,
                      NoRefCountPolicy        > MFUncountedShaderTextureFilterPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribImageProcessingFieldSFields \ingroup GrpLibOSGContribImageProcessing */
struct SFRecShaderTextureFilterPtr : 
    public PointerSField<ShaderTextureFilter *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribImageProcessingFieldSFields \ingroup GrpLibOSGContribImageProcessing */
struct SFUnrecShaderTextureFilterPtr : 
    public PointerSField<ShaderTextureFilter *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribImageProcessingFieldSFields \ingroup GrpLibOSGContribImageProcessing */
struct SFWeakShaderTextureFilterPtr :
    public PointerSField<ShaderTextureFilter *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribImageProcessingFieldSFields \ingroup GrpLibOSGContribImageProcessing */
struct SFUncountedShaderTextureFilterPtr :
    public PointerSField<ShaderTextureFilter *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribImageProcessingFieldMFields \ingroup GrpLibOSGContribImageProcessing */
struct MFRecShaderTextureFilterPtr :
    public PointerMField<ShaderTextureFilter *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribImageProcessingFieldMFields \ingroup GrpLibOSGContribImageProcessing */
struct MFUnrecShaderTextureFilterPtr :
    public PointerMField<ShaderTextureFilter *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribImageProcessingFieldMFields \ingroup GrpLibOSGContribImageProcessing */
struct MFWeakShaderTextureFilterPtr :
    public PointerMField<ShaderTextureFilter *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribImageProcessingFieldMFields \ingroup GrpLibOSGContribImageProcessing */
struct MFUncountedShaderTextureFilterPtr :
    public PointerMField<ShaderTextureFilter *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSHADERTEXTUREFILTERFIELDS_H_ */
