/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETRIGIDBODYFIELDS_H_
#define _OSGBULLETRIGIDBODYFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletRigidBody;

OSG_GEN_CONTAINERPTR(BulletRigidBody);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletRigidBody *> :
    public FieldTraitsFCPtrBase<BulletRigidBody *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletRigidBody *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletRigidBodyPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletRigidBodyPtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletRigidBodyPtr"; 
}


/*! \ingroup GrpContribBulletFieldTraits
 */
template <>
struct FieldTraits<BulletRigidBody *, 1> :
    public FieldTraitsFCPtrBase<BulletRigidBody *, 1>
{
  private:

  public:
    typedef FieldTraits<BulletRigidBody *, 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildBulletRigidBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletRigidBody *, 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildBulletRigidBodyPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletRigidBody *,
                      RecordedRefCountPolicy  > SFRecBulletRigidBodyPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletRigidBody *,
                      UnrecordedRefCountPolicy> SFUnrecBulletRigidBodyPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletRigidBody *,
                      WeakRefCountPolicy      > SFWeakBulletRigidBodyPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletRigidBody *,
                      NoRefCountPolicy        > SFUncountedBulletRigidBodyPtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletRigidBody *,
                      RecordedRefCountPolicy  > MFRecBulletRigidBodyPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletRigidBody *,
                      UnrecordedRefCountPolicy> MFUnrecBulletRigidBodyPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletRigidBody *,
                      WeakRefCountPolicy      > MFWeakBulletRigidBodyPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletRigidBody *,
                      NoRefCountPolicy        > MFUncountedBulletRigidBodyPtr;



/*! \ingroup GrpContribBulletFieldMFields */
typedef ChildPointerMField<
          BulletRigidBody *, 
          UnrecordedRefCountPolicy,
          1             > MFUnrecChildBulletRigidBodyPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletRigidBodyPtr : 
    public PointerSField<BulletRigidBody *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletRigidBodyPtr : 
    public PointerSField<BulletRigidBody *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletRigidBodyPtr :
    public PointerSField<BulletRigidBody *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletRigidBodyPtr :
    public PointerSField<BulletRigidBody *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletRigidBodyPtr :
    public PointerMField<BulletRigidBody *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletRigidBodyPtr :
    public PointerMField<BulletRigidBody *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletRigidBodyPtr :
    public PointerMField<BulletRigidBody *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletRigidBodyPtr :
    public PointerMField<BulletRigidBody *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecChildBulletRigidBodyPtr :
    public ChildPointerMField<
        BulletRigidBody *, 
        UnrecordedRefCountPolicy,
        1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETRIGIDBODYFIELDS_H_ */
