/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBULLETSOFTBODYFIELDS_H_
#define _OSGBULLETSOFTBODYFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribBulletDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class BulletSoftBody;

OSG_GEN_CONTAINERPTR(BulletSoftBody);

/*! \ingroup GrpContribBulletFieldTraits
    \ingroup GrpLibOSGContribBullet
 */
template <>
struct FieldTraits<BulletSoftBody *> :
    public FieldTraitsFCPtrBase<BulletSoftBody *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<BulletSoftBody *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBBULLET_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFBulletSoftBodyPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFBulletSoftBodyPtr"; }
};

template<> inline
const Char8 *FieldTraits<BulletSoftBody *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBulletSoftBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftBody *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBulletSoftBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftBody *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBulletSoftBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftBody *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBulletSoftBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftBody *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBulletSoftBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftBody *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBulletSoftBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftBody *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBulletSoftBodyPtr"; 
}

template<> inline
const Char8 *FieldTraits<BulletSoftBody *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBulletSoftBodyPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSoftBody *,
                      RecordedRefCountPolicy  > SFRecBulletSoftBodyPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSoftBody *,
                      UnrecordedRefCountPolicy> SFUnrecBulletSoftBodyPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSoftBody *,
                      WeakRefCountPolicy      > SFWeakBulletSoftBodyPtr;
/*! \ingroup GrpContribBulletFieldSFields */
typedef PointerSField<BulletSoftBody *,
                      NoRefCountPolicy        > SFUncountedBulletSoftBodyPtr;


/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSoftBody *,
                      RecordedRefCountPolicy  > MFRecBulletSoftBodyPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSoftBody *,
                      UnrecordedRefCountPolicy> MFUnrecBulletSoftBodyPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSoftBody *,
                      WeakRefCountPolicy      > MFWeakBulletSoftBodyPtr;
/*! \ingroup GrpContribBulletFieldMFields */
typedef PointerMField<BulletSoftBody *,
                      NoRefCountPolicy        > MFUncountedBulletSoftBodyPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFRecBulletSoftBodyPtr : 
    public PointerSField<BulletSoftBody *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUnrecBulletSoftBodyPtr : 
    public PointerSField<BulletSoftBody *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFWeakBulletSoftBodyPtr :
    public PointerSField<BulletSoftBody *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldSFields \ingroup GrpLibOSGContribBullet */
struct SFUncountedBulletSoftBodyPtr :
    public PointerSField<BulletSoftBody *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFRecBulletSoftBodyPtr :
    public PointerMField<BulletSoftBody *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUnrecBulletSoftBodyPtr :
    public PointerMField<BulletSoftBody *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFWeakBulletSoftBodyPtr :
    public PointerMField<BulletSoftBody *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribBulletFieldMFields \ingroup GrpLibOSGContribBullet */
struct MFUncountedBulletSoftBodyPtr :
    public PointerMField<BulletSoftBody *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBULLETSOFTBODYFIELDS_H_ */
